import { AgreementSection } from './types';

export const DEFAULT_TEMPLATE_NAME = 'Exclusive Advisory Agreement';
export const DEFAULT_TEMPLATE_DESCRIPTION = 'Standard exclusive advisory agreement template for 5th Line Capital Advisors engagements.';

export const DEFAULT_SECTIONS: Omit<AgreementSection, 'id' | 'db_id' | 'template_id'>[] = [
  {
    section_id: 'preamble',
    title: 'Preamble',
    category: 'staple',
    enabled: true,
    sort_order: 0,
    description: 'Opening paragraph establishing the parties and purpose of the agreement.',
    template_text: `This {{agreement_type}} ("Agreement") is executed by and between 5th Line Capital Advisors LLC, a Delaware limited liability company ("5th Line") and {{company_name}}{{company_entity_type_clause}}, its affiliates, subsidiaries and assigns ("{{company_short}}"). This Agreement is to acknowledge and protect the experience, value, expertise and continued exclusive working relationship between {{company_short}} and 5th Line, and lenders, warehouse lines, funds, banks and/or investors ("Source") that may assist with {{company_short}}'s ongoing debt needs. In consideration of the mutual promises and covenants herein contained, 5th Line and {{company_short}} agree as follows:`,
    fields: [
      { key: 'agreement_type', label: 'Agreement Type', type: 'text', defaultValue: 'Exclusive Advisory Agreement', placeholder: 'e.g. Exclusive Advisory Agreement' },
      { key: 'company_name', label: 'Company Name', type: 'text', defaultValue: 'COMPANY', placeholder: 'Full legal entity name' },
      { key: 'company_entity_type', label: 'Entity Type', type: 'text', defaultValue: '', placeholder: 'e.g. a Delaware corporation' },
      { key: 'company_short', label: 'Short Name', type: 'text', defaultValue: 'Company', placeholder: 'e.g. Company or Acme' },
    ],
    subsections: null,
    qualifiers: null,
  },
  {
    section_id: 'services',
    title: 'Services',
    category: 'staple',
    enabled: true,
    sort_order: 1,
    description: 'Defines the scope of services and exclusivity.',
    template_text: `Services. {{company_short}} hereby engages 5th Line on an {{exclusivity}} basis during the Term to {{service_scope}} (collectively, "Services").`,
    fields: [
      { key: 'exclusivity', label: 'Exclusivity', type: 'select', defaultValue: 'exclusive', options: ['exclusive', 'non-exclusive'] },
      { key: 'service_scope', label: 'Service Scope', type: 'textarea', defaultValue: 'provide financial advice related to the sourcing of debt capital for Company, including assisting Company in approaching and negotiating with potential lenders of funds for potential debt financing ("Financing"), providing administrative support, and non-securities related services' },
    ],
    subsections: null,
    qualifiers: null,
  },
  {
    section_id: 'compensation',
    title: 'Compensation',
    category: 'configurable',
    enabled: true,
    sort_order: 2,
    description: 'Fee structure including signing, term sheet, and closing fees.',
    template_text: `Compensation. {{comp_intro}} The Consulting Fee shall be payable as follows:`,
    fields: [
      { key: 'comp_intro', label: 'Compensation Introduction', type: 'textarea', defaultValue: 'In consideration for the Services, Company shall pay to 5th Line a consulting fee (the "Consulting Fee") based on the following structure.' },
    ],
    subsections: [
      {
        id: 'signing_fee',
        title: 'Signing Fee',
        enabled: true,
        fields: [
          { key: 'signing_fee', label: 'Signing Fee Amount', type: 'text', defaultValue: '$15,500' },
          { key: 'signing_refundable', label: 'Refundability', type: 'select', defaultValue: 'non-refundable', options: ['non-refundable', 'refundable', 'partially refundable'] },
        ],
        template_text: `A {{signing_refundable}} signing fee of {{signing_fee}} shall be due and payable upon execution of this Agreement.`,
      },
      {
        id: 'termsheet_fee',
        title: 'Term Sheet Fee',
        enabled: true,
        fields: [
          { key: 'termsheet_fee', label: 'Term Sheet Fee Amount', type: 'text', defaultValue: '$25,000' },
          { key: 'termsheet_refundable', label: 'Refundability', type: 'select', defaultValue: 'non-refundable', options: ['non-refundable', 'refundable', 'partially refundable'] },
        ],
        template_text: `A {{termsheet_refundable}} term sheet fee of {{termsheet_fee}} shall be due and payable upon delivery of a Qualified Term Sheet (as defined in Exhibit A).`,
      },
      {
        id: 'closing_fee_introduced',
        title: 'Closing Fee (Introduced Sources)',
        enabled: true,
        fields: [
          { key: 'closing_min', label: 'Minimum Fee', type: 'text', defaultValue: '$XXX,000' },
          { key: 'closing_pct', label: 'Fee Percentage', type: 'text', defaultValue: '2.5%' },
          { key: 'tail_period', label: 'Tail Period', type: 'text', defaultValue: '3 months' },
        ],
        template_text: `A closing fee equal to the greater of {{closing_min}} or {{closing_pct}} of the total commitment amount from Sources introduced by 5th Line, payable upon closing. This fee shall survive termination for a period of {{tail_period}} (the "Tail Period").`,
      },
      {
        id: 'closing_fee_exhibit_b',
        title: 'Closing Fee (Exhibit B Sources)',
        enabled: true,
        fields: [
          { key: 'exhibit_b_min', label: 'Minimum Fee', type: 'text', defaultValue: '$XXX,000' },
          { key: 'exhibit_b_pct', label: 'Fee Percentage', type: 'text', defaultValue: '1.5%' },
          { key: 'exhibit_b_tail', label: 'Tail Period', type: 'text', defaultValue: '3 months' },
        ],
        template_text: `A closing fee equal to the greater of {{exhibit_b_min}} or {{exhibit_b_pct}} of the total commitment amount from Exhibit B Sources, payable upon closing. This fee shall survive termination for a period of {{exhibit_b_tail}}.`,
      },
    ],
    qualifiers: null,
  },
  {
    section_id: 'confidential_information',
    title: 'Confidential Information',
    category: 'staple',
    enabled: true,
    sort_order: 3,
    description: 'Confidentiality obligations and marketing permissions.',
    template_text: `Confidential Information. Each party agrees that all information disclosed by one party to the other in connection with this Agreement shall be treated as confidential. {{company_short}} {{marketing_permission_text}} 5th Line permission to use {{company_short}}'s name and logo for marketing purposes{{marketing_includes_clause}}.`,
    fields: [
      { key: 'marketing_permission', label: 'Marketing Permission', type: 'select', defaultValue: 'granted', options: ['granted', 'not granted'] },
      { key: 'marketing_includes', label: 'Marketing Includes', type: 'text', defaultValue: ', including on its website and pitch materials', placeholder: 'Additional marketing scope' },
    ],
    subsections: null,
    qualifiers: null,
  },
  {
    section_id: 'term',
    title: 'Term',
    category: 'configurable',
    enabled: true,
    sort_order: 4,
    description: 'Duration, termination, and tail provisions.',
    template_text: `Term. This Agreement shall be effective as of the date of execution and shall remain in effect for a period of twelve (12) months (the "Term"). Either party may terminate this Agreement upon {{notice_period}} days' written notice. Notwithstanding termination, the fee provisions shall survive for a general tail period of {{general_tail}} for transactions above {{tail_threshold}}, and {{introduced_tail}} for Sources introduced by 5th Line during the Term.`,
    fields: [
      { key: 'notice_period', label: 'Notice Period (days)', type: 'text', defaultValue: '30' },
      { key: 'general_tail', label: 'General Tail Period', type: 'text', defaultValue: '3 months' },
      { key: 'tail_threshold', label: 'Tail Threshold', type: 'text', defaultValue: '$1,000,000' },
      { key: 'introduced_tail', label: 'Introduced Sources Tail', type: 'text', defaultValue: '12 months' },
    ],
    subsections: null,
    qualifiers: null,
  },
  {
    section_id: 'indemnification',
    title: 'Indemnification',
    category: 'staple',
    enabled: true,
    sort_order: 5,
    description: 'Mutual indemnification provisions.',
    template_text: `Indemnification. {{indemnification_text}}`,
    fields: [
      { key: 'indemnification_text', label: 'Indemnification Text', type: 'textarea', defaultValue: 'Each party (the "Indemnifying Party") shall indemnify, defend and hold harmless the other party and its officers, directors, employees, agents and representatives (collectively, the "Indemnified Party") from and against any and all losses, damages, liabilities, costs and expenses (including reasonable attorneys\' fees) arising out of or relating to any breach of this Agreement by the Indemnifying Party or any negligent or wrongful act or omission of the Indemnifying Party in connection with this Agreement.' },
    ],
    subsections: null,
    qualifiers: null,
  },
  {
    section_id: 'non_circumvention',
    title: 'Non-Circumvention',
    category: 'staple',
    enabled: true,
    sort_order: 6,
    description: 'Prevents parties from bypassing the agreement.',
    template_text: `Non-Circumvention. {{non_circumvention_text}}`,
    fields: [
      { key: 'non_circumvention_text', label: 'Non-Circumvention Text', type: 'textarea', defaultValue: 'Company agrees that during the Term and for a period of twenty-four (24) months following termination of this Agreement, Company shall not, directly or indirectly, contact, solicit, negotiate with, or enter into any agreement with any Source introduced by 5th Line without the prior written consent of 5th Line. Any attempt to circumvent this provision shall entitle 5th Line to the full Consulting Fee that would have been payable had the transaction been completed through 5th Line.' },
    ],
    subsections: null,
    qualifiers: null,
  },
  {
    section_id: 'equitable_relief',
    title: 'Equitable Relief',
    category: 'optional',
    enabled: true,
    sort_order: 7,
    description: 'Equitable remedies for breach of agreement.',
    template_text: `Equitable Relief. {{equitable_relief_text}}`,
    fields: [
      { key: 'equitable_relief_text', label: 'Equitable Relief Text', type: 'textarea', defaultValue: 'Each party acknowledges that a breach of the confidentiality, non-circumvention, or exclusivity provisions of this Agreement may cause irreparable harm to the other party for which monetary damages would be an inadequate remedy. Accordingly, in addition to any other remedies available at law or in equity, the non-breaching party shall be entitled to seek injunctive or other equitable relief to prevent or restrain any such breach, without the necessity of proving actual damages or posting any bond or security.' },
    ],
    subsections: null,
    qualifiers: null,
  },
  {
    section_id: 'miscellaneous',
    title: 'Miscellaneous',
    category: 'staple',
    enabled: true,
    sort_order: 8,
    description: 'Governing law and general provisions.',
    template_text: `Miscellaneous. This Agreement shall be governed by and construed in accordance with the laws of the State of {{governing_state}}, without regard to its conflicts of law principles. This Agreement constitutes the entire agreement between the parties with respect to the subject matter hereof and supersedes all prior agreements and understandings, whether written or oral.`,
    fields: [
      { key: 'governing_state', label: 'Governing State', type: 'text', defaultValue: 'Delaware' },
    ],
    subsections: null,
    qualifiers: null,
  },
  {
    section_id: 'exhibit_a',
    title: 'Exhibit A — Qualified Term Sheet',
    category: 'configurable',
    enabled: true,
    sort_order: 9,
    description: 'Defines qualifications for a valid term sheet.',
    template_text: `EXHIBIT A`,
    fields: [
      { key: 'exhibit_a_min_qualifiers', label: 'Minimum Qualifiers Required', type: 'text', defaultValue: '2' },
    ],
    subsections: null,
    qualifiers: [
      { id: 'qa', letter: 'a', text: 'An interest rate no greater than 13.5%', enabled: true },
      { id: 'qb', letter: 'b', text: 'Total Funding Commitment of at least $10.0MM', enabled: true },
      { id: 'qc', letter: 'c', text: 'An interest-only period of at least six (6) months', enabled: true },
      { id: 'qd', letter: 'd', text: 'No personal guarantees', enabled: true },
    ],
  },
  {
    section_id: 'exhibit_b',
    title: 'Exhibit B — Excluded Lenders',
    category: 'configurable',
    enabled: true,
    sort_order: 10,
    description: 'Lists lenders excluded from the advisory engagement.',
    template_text: `EXHIBIT B`,
    fields: [],
    subsections: null,
    qualifiers: [
      { id: 'eb_a', letter: 'a', text: 'River Capital Group Holdings', enabled: true },
      { id: 'eb_b', letter: 'b', text: 'Quaestor Advisors', enabled: true },
      { id: 'eb_c', letter: 'c', text: 'Boathouse Capital', enabled: true },
      { id: 'eb_d', letter: 'd', text: 'Stephens Inc', enabled: true },
      { id: 'eb_e', letter: 'e', text: 'Prosperity Bank', enabled: true },
      { id: 'eb_f', letter: 'f', text: 'Beal Private Capital', enabled: true },
    ],
  },
];
