export const COUNTRY_OPTIONS = [
  'Albania',
  'Andorra',
  'Antigua and Barbuda',
  'Armenia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Canada',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia (Czech Republic)',
  'Denmark',
  'Dominica',
  'Dominican Republic',
  'El Salvador',
  'Estonia',
  'Finland',
  'France',
  'Georgia',
  'Germany',
  'Greece',
  'Grenada',
  'Guatemala',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'Ireland',
  'Italy',
  'Jamaica',
  'Kazakhstan',
  'Kosovo',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Mexico',
  'Moldova',
  'Monaco',
  'Montenegro',
  'Netherlands',
  'Nicaragua',
  'North Macedonia',
  'Norway',
  'Panama',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'San Marino',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
  'Switzerland',
  'Trinidad and Tobago',
  'Turkey',
  'Ukraine',
  'United Kingdom (U.K / Great Britain / England)',
  'Scotland',
  'United States of America',
  'Vatican City (Holy See)',
].map((c) => ({ value: c, label: c }));