export const COMPANY_REQUIREMENT_OPTIONS = [
  '12 Months+ Runway Pre-Debt',
  'Asset Base',
  'Burn <50% of top line revenue',
  'Clear path to Profitability',
  'Defendable IP',
  'Fully Commercialized Product or Service',
  'Gross Margins above 65%',
  'Growth above 20%',
  'IP Portfolio',
  'Less Equity Investment Historically',
  'Little Customer Concentration',
  'Majority US Headcount',
  'Majority US or Canada Headcount',
  'Majority US or Canada Revenue',
  'Majority US Revenue',
  'No Regulatory Risk',
  'Recent Equity Funding',
  'Recurring OR Reoccurring Revenue',
  'Strong Customer / Revenue Retention',
  'Top Tier VC or PE',
  'True Recurring Revenue Streams',
] as const;
