export const GEO_OPTIONS = [
  'Agnostic',
  'United States',
  'Canada',
  'North America',
  'Americas',
  'Europe',
  'UK',
  'Asia',
  'Middle East',
  'Africa',
  'Oceania',
  'Australia',
  'South America',
  'Central America',
  'Global',
  // US Regions
  'Northeast',
  'Southeast',
  'Midwest',
  'Southwest',
  'West Coast',
  // US States (most common)
  'California',
  'New York',
  'Texas',
  'Florida',
  'Illinois',
  'Colorado',
  'Georgia',
  'Massachusetts',
  'Pennsylvania',
  'Ohio',
  'Virginia',
  'Washington',
  'Arizona',
  'Tennessee',
  'Alabama',
  'Arkansas',
  'Delaware',
  'District of Columbia',
  'Louisiana',
  'New Mexico',
  'Utah',
] as const;
