export const INDUSTRY_OPTIONS = [
  "Agnostic",
  "Consumer Goods",
  "Clothing & Apparel",
  "Food & Beverage",
  "Ecommerce",
  "Professional Services",
  "Tech-Enabled Services & MSPs",
  "Technology",
  "SaaS",
  "Hardware",
  "Telecommunications",
  "Media & Entertainment",
  "Casinos & Gaming",
  "Hospitality (Hotels, Restaurants, etc.)",
  "Financial Services",
  "Real Estate",
  "Construction",
  "Manufacturing & Industrial",
  "Automotive",
  "Aerospace",
  "Transportation",
  "Energy",
  "Oil & Gas",
  "Mining",
  "Healthcare",
  "Biotech & Life Science",
  "Medical Device",
  "Education",
] as const;

/** Pre-consolidation tags (Sept 2026), folded into INDUSTRY_OPTIONS. Never offer these again. */
export const LEGACY_INDUSTRY_OPTIONS: readonly string[] = [
  "AI/ML",
  "Accessories",
  "Accounting",
  "Aerospace & Defense",
  "Agricultural Chemicals",
  "Agriculture",
  "Air",
  "Aluminum Mining",
  "Animal Husbandry",
  "Animal Textiles",
  "Apparel and Accessories",
  "Application Specific Semiconductors",
  "Aquaculture",
  "Asset Management",
  "Audit and Tax Services (B2B)",
  "Audit and Tax Services (B2C)",
  "Automative",
  "Automotive Insurance",
  "B2B Services",
  "BPO/Outsource Services",
  "Beverages",
  "Biotechnology",
  "Broadcasting",
  "Brokerage",
  "Building Products",
  "Buildings and Property",
  "Business Equipment and Supplies",
  "Business Products and Services (B2B)",
  "Business Services",
  "Cable Service Providers",
  "Cannabis",
  "Capital Markets/Institutions",
  "Casinos and Gaming",
  "Catalog Retail",
  "Chemicals and Gases",
  "Clean Tech",
  "Clinics/Outpatient Services",
  "Clothing",
  "Cloud Infrastructure",
  "Coal Mining",
  "Coal and Consumable Fuels Equipment",
  "Commercial Banks",
  "Commercial Products",
  "Commercial Services",
  "Commercial Transportation",
  "Commercial/Professional Insurance",
  "Commodity Chemicals",
  "Communications and Networking",
  "Computer Hardware",
  "Computers",
  "Conglomerates",
  "Connectivity Products",
  "Construction (Non-Wood)",
  "Construction and Engineering",
  "Consulting Services (B2B)",
  "Containers and Packaging",
  "Cruise Lines",
  "Cultivation",
  "DTC",
  "Decision/Risk Analysis",
  "Department Stores",
  "Diagnostic Equipment",
  "Discovery Tools (Healthcare)",
  "Distribution",
  "Distributors (Healthcare)",
  "Distributors/Wholesale",
  "Distributors/Wholesale (B2C)",
  "Drug Delivery",
  "Drug Discovery",
  "Education and Training Services (B2B)",
  "Educational and Training Services (B2C)",
  "Elder and Disabled Care",
  "Electric Utilities",
  "Electrical Equipment",
  "Electronic Components",
  "Electronic Equipment and Instruments",
  "Electronics (B2C)",
  "Enterprise Systems (Healthcare)",
  "Environmental",
  "Environmental Services (B2B)",
  "Exploration",
  "Fiberoptic Equipment",
  "Fintech",
  "Food Products",
  "Footwear",
  "Forestry",
  "Forestry Development/Harvesting",
  "Forestry Processing",
  "Franchising",
  "Gas Utilities",
  "General Merchandise Stores",
  "General Purpose Semiconductors",
  "Gold Mining",
  "Government",
  "Government Services",
  "Healthcare Devices and Supplies",
  "Healthcare IT",
  "Healthcare Services",
  "Healthcare Technology Systems",
  "Holding Companies",
  "Home Furnishings",
  "Horticulture",
  "Hospitality",
  "Hospitals/Inpatient Services",
  "Hotels and Leisure",
  "Hotels and Resorts",
  "Household Appliances",
  "Household Products",
  "Human Capital Services",
  "IT Consulting and Outsourcing",
  "IT Services",
  "Industrial",
  "Information Services (B2C)",
  "Information Technology",
  "Infrastructure",
  "Insurance",
  "Insurance Brokers",
  "International Banks",
  "Internet Retail",
  "Internet Service Providers",
  "Investment Banks",
  "Iron and Steel Mining",
  "Laboratory Services (Healthcare)",
  "Legal Services (B2B)",
  "Legal Services (B2C)",
  "Leisure Facilities",
  "Life Science",
  "Life and Health Insurance",
  "Logistics",
  "Luxury Goods",
  "Machinery (B2B)",
  "Managed Care",
  "Manufacturing",
  "Marine",
  "Materials and Resources",
  "Med Tech",
  "Media",
  "Media & Telecommunication",
  "Media and Information Services (B2B)",
  "Medical Records Systems",
  "Medical Supplies",
  "Metal Containers and Packaging",
  "Metals",
  "Metals & Mining",
  "Mineral Textiles",
  "Minerals and Mining",
  "Mining & Commodities",
  "Monitoring Equipment",
  "Movies",
  "Multi-Utilities",
  "Multi-line Chemicals",
  "Multi-line Insurance",
  "Multi-line Mining",
  "Music and Entertainment",
  "National Banks",
  "Office Electronics",
  "Office Services (B2B)",
  "Oil and Gas",
  "Oil and Gas Equipment",
  "Other Agriculture",
  "Other Apparel",
  "Other Business Products and Services",
  "Other Capital Markets/Institutions",
  "Other Chemicals and Gases",
  "Other Commercial Banks",
  "Other Commercial Products",
  "Other Commercial Services",
  "Other Communications and Networking",
  "Other Containers and Packaging",
  "Other Devices and Supplies",
  "Other Equipment",
  "Other Forestry",
  "Other Hardware",
  "Other Healthcare",
  "Other Healthcare Services",
  "Other Healthcare Technology Systems",
  "Other IT Services",
  "Other Information Technology",
  "Other Insurance",
  "Other Materials",
  "Other Media",
  "Other Metals",
  "Other Pharmaceuticals and Biotechnology",
  "Other Restaurants",
  "Other Retail",
  "Other Semiconductors",
  "Other Services (B2C Non-Financial)",
  "Other Textiles",
  "Other Transportation",
  "Other Utilities",
  "Outcome Management (Healthcare)",
  "Paper Containers and Packaging",
  "Paper/Soft Products",
  "Parts and Peripherals",
  "Personal Products",
  "Pharmaceuticals",
  "Pharmaceuticals and Biotechnology",
  "Plant Textiles",
  "Plastic Containers and Packaging",
  "Practice Management (Healthcare)",
  "Precious Metals and Minerals Mining",
  "Printing Services (B2B)",
  "Private Equity",
  "Production (Semiconductors)",
  "Production and Refining",
  "Property and Casualty Insurance",
  "Publishing",
  "Radio and Television",
  "Rail",
  "Raw Materials (Non-Wood)",
  "Re-Insurance",
  "Real Estate Investment Trusts (REITs)",
  "Real Estate Services (B2C)",
  "Recreational Goods",
  "Regional Banks",
  "Restaurants",
  "Restaurants and Bars",
  "Retail",
  "Road",
  "Security Services (B2B)",
  "Semiconductors",
  "Services",
  "Services (Non-Financial)",
  "Social Content",
  "Software",
  "Special Purpose Acquisition Company (SPAC)",
  "Specialty Chemicals",
  "Specialty Retail",
  "Staffing",
  "Storage (IT)",
  "Surgical Devices",
  "Sustainability",
  "Synthetic Textiles",
  "Systems and Information Management",
  "Tech-Enabled Hardware",
  "Tech-Enabled Services",
  "Technology & Software",
  "Telecom",
  "Telecommunications Service Providers",
  "Textiles",
  "Therapeutic Devices",
  "Transportation & Logistics",
  "Utilities",
  "Water Utilities",
  "Wireless Communications Equipment",
  "Wireless Service Providers",
  "Wood Containers and Packaging",
  "Wood/Hard Products",
];

