export const INDUSTRY_OPTIONS = [
  'Accessories',
  'Accounting',
  'Aerospace & Defense',
  'Agnostic',
  'Agricultural Chemicals',
  'Agriculture',
  'AI/ML',
  'Air',
  'Alternative Energy Equipment',
  'Aluminum Mining',
  'Animal Husbandry',
  'Animal Textiles',
  'Apparel and Accessories',
  'Application Software',
  'Application Specific Semiconductors',
  'Aquaculture',
  'Asset Management',
  'Audit and Tax Services (B2B)',
  'Audit and Tax Services (B2C)',
  'Automation/Workflow Software',
  'Automotive',
  'Automotive Insurance',
  'B2B Services',
  'Beverages',
  'Biotechnology',
  'BPO/Outsource Services',
  'Broadcasting',
  'Brokerage',
  'Building Products',
  'Buildings and Property',
  'Business Equipment and Supplies',
  'Business Products and Services (B2B)',
  'Business/Productivity Software',
  'Cable Service Providers',
  'Cannabis',
  'Capital Markets/Institutions',
  'Casinos and Gaming',
  'Catalog Retail',
  'Chemicals and Gases',
  'Clean Energy',
  'Clean Tech',
  'Clinics/Outpatient Services',
  'Clothing',
  'Cloud Infrastructure',
  'Coal and Consumable Fuels Equipment',
  'Coal Mining',
  'Commercial and Industrial',
  'Commercial Banks',
  'Commercial Products',
  'Commercial Services',
  'Commercial Transportation',
  'Commercial/Professional Insurance',
  'Commodity Chemicals',
  'Communication Software',
  'Communications and Networking',
  'Computer Hardware',
  'Computers',
  'Conglomerates',
  'Connectivity Products',
  'Construction',
  'Construction (Non-Wood)',
  'Construction and Engineering',
  'Consulting Services (B2B)',
  'Consumer',
  'Consumer (Products & Services)',
  'Consumer Durables',
  'Consumer Finance',
  'Consumer Goods',
  'Consumer Non-Durables',
  'Consumer Products and Services (B2C)',
  'Containers and Packaging',
  'Cruise Lines',
  'Cultivation',
  'Database Software',
  'Decision/Risk Analysis',
  'Department Stores',
  'Diagnostic Equipment',
  'Discovery Tools (Healthcare)',
  'Distribution',
  'Distributors (Healthcare)',
  'Distributors/Wholesale',
  'Distributors/Wholesale (B2C)',
  'Drug Delivery',
  'Drug Discovery',
  'DTC',
  'ECommerce',
  'Education',
  'Education and Training Services (B2B)',
  'Educational and Training Services (B2C)',
  'Educational Software',
  'Elder and Disabled Care',
  'Electric Utilities',
  'Electrical Equipment',
  'Electronic Components',
  'Electronic Equipment and Instruments',
  'Electronics (B2C)',
  'Energy',
  'Energy Equipment',
  'Energy Exploration',
  'Energy Infrastructure',
  'Energy Marketing',
  'Energy Production',
  'Energy Refining',
  'Energy Services',
  'Energy Storage',
  'Energy Traders and Brokers',
  'Energy Transportation',
  'Enterprise Systems (Healthcare)',
  'Entertainment Software',
  'Environmental',
  'Environmental Services (B2B)',
  'Exploration',
  'Fiberoptic Equipment',
  'Finance',
  'Financial Services',
  'Financial Software',
  'Fintech',
  'Food & Beverage',
  'Food Products',
  'Footwear',
  'Forestry',
  'Forestry Development/Harvesting',
  'Forestry Processing',
  'Franchising',
  'Gas Utilities',
  'General Merchandise Stores',
  'General Purpose Semiconductors',
  'Gold Mining',
  'Government',
  'Government Services',
  'hardware',
  'Healthcare',
  'Healthcare Devices and Supplies',
  'Healthcare IT',
  'Healthcare Services',
  'Healthcare Technology Systems',
  'Holding Companies',
  'Home Furnishings',
  'Horticulture',
  'Hospitality',
  'Hospitals/Inpatient Services',
  'Hotels and Leisure',
  'Hotels and Resorts',
  'Household Appliances',
  'Household Products',
  'Human Capital Services',
  'Industrial',
  'Industrial Chemicals',
  'Industrial Supplies and Parts',
  'Industrials',
  'Information Services (B2C)',
  'Information Technology',
  'Infrastructure',
  'Insurance',
  'Insurance Brokers',
  'International Banks',
  'Internet Retail',
  'Internet Service Providers',
  'Internet Software',
  'Investment Banks',
  'Iron and Steel Mining',
  'IT Consulting and Outsourcing',
  'IT Services',
  'Laboratory Services (Healthcare)',
  'Legal Services (B2B)',
  'Legal Services (B2C)',
  'Leisure Facilities',
  'Life and Health Insurance',
  'Life Science',
  'Logistics',
  'Luxury Goods',
  'Machinery (B2B)',
  'Managed Care',
  'Manufacturing',
  'Marine',
  'Materials and Resources',
  'Med Tech',
  'Media',
  'Media & Telecommunication',
  'Media and Information Services (B2B)',
  'Medical Records Systems',
  'Medical Supplies',
  'Metal Containers and Packaging',
  'Metals',
  'Metals & Mining',
  'Mineral Textiles',
  'Minerals and Mining',
  'Mining & Commodities',
  'Monitoring Equipment',
  'Movies',
  'Multi-line Chemicals',
  'Multi-line Insurance',
  'Multi-line Mining',
  'Multi-Utilities',
  'Multimedia and Design Software',
  'Music and Entertainment',
  'National Banks',
  'Network Management Software',
  'Office Electronics',
  'Office Services (B2B)',
  'Oil & Gas',
  'Oil and Gas Equipment',
  'Operating Systems Software',
  'Other Agriculture',
  'Other Apparel',
  'Other Business Products and Services',
  'Other Capital Markets/Institutions',
  'Other Chemicals and Gases',
  'Other Commercial Banks',
  'Other Commercial Products',
  'Other Commercial Services',
  'Other Communications and Networking',
  'Other Consumer Durables',
  'Other Consumer Non-Durables',
  'Other Consumer Products and Services',
  'Other Containers and Packaging',
  'Other Devices and Supplies',
  'Other Energy',
  'Other Energy Services',
  'Other Equipment',
  'Other Financial Services',
  'Other Forestry',
  'Other Hardware',
  'Other Healthcare',
  'Other Healthcare Services',
  'Other Healthcare Technology Systems',
  'Other Information Technology',
  'Other Insurance',
  'Other IT Services',
  'Other Materials',
  'Other Media',
  'Other Metals',
  'Other Pharmaceuticals and Biotechnology',
  'Other Restaurants',
  'Other Retail',
  'Other Semiconductors',
  'Other Services (B2C Non-Financial)',
  'Other Software',
  'Other Textiles',
  'Other Transportation',
  'Other Utilities',
  'Outcome Management (Healthcare)',
  'Paper Containers and Packaging',
  'Paper/Soft Products',
  'Parts and Peripherals',
  'Personal Products',
  'Pharmaceuticals',
  'Pharmaceuticals and Biotechnology',
  'Plant Textiles',
  'Plastic Containers and Packaging',
  'Practice Management (Healthcare)',
  'Precious Metals and Minerals Mining',
  'Printing Services (B2B)',
  'Private Equity',
  'Production (Semiconductors)',
  'Production and Refining',
  'Property and Casualty Insurance',
  'Publishing',
  'Radio and Television',
  'Rail',
  'Raw Materials (Non-Wood)',
  'Re-Insurance',
  'Real Estate',
  'Real Estate Investment Trusts (REITs)',
  'Real Estate Services (B2C)',
  'Recreational Goods',
  'Regional Banks',
  'Restaurants',
  'Restaurants and Bars',
  'Retail',
  'Road',
  'SaaS',
  'Security Services (B2B)',
  'Semiconductors',
  'Services',
  'Services (Non-Financial)',
  'Social Content',
  'Social/Platform Software',
  'Software',
  'Software Development Applications',
  'Special Purpose Acquisition Company (SPAC)',
  'Specialized Finance',
  'Specialty Chemicals',
  'Specialty Retail',
  'Staffing',
  'Storage (IT)',
  'Surgical Devices',
  'Sustainability',
  'Synthetic Textiles',
  'Systems and Information Management',
  'Tech-Enabled Hardware',
  'Tech-Enabled Services',
  'Technology',
  'Telecom',
  'Telecommunications Service Providers',
  'Textiles',
  'Therapeutic Devices',
  'Thrifts and Mortgage Finance',
  'Transportation',
  'Transportation & Logistics',
  'Utilities',
  'Vertical Market Software',
  'Water Utilities',
  'Wireless Communications Equipment',
  'Wireless Service Providers',
  'Wood Containers and Packaging',
  'Wood/Hard Products',
] as const;
