export const INDUSTRY_OPTIONS = [
  'Aerospace & Defense',
  'Agnostic',
  'Agriculture',
  'B2B Services',
  'Cannabis',
  'Clean Tech',
  'Commercial and Industrial',
  'Construction',
  'Consumer (Products & Services)',
  'Consumer Goods',
  'Distribution',
  'ECommerce',
  'Education',
  'Energy',
  'Environmental',
  'Finance',
  'Food & Beverage',
  'Franchising',
  'Government',
  'Healthcare',
  'Healthcare Services',
  'Industrials',
  'Life Science',
  'Manufacturing',
  'Med Tech',
  'Media & Telecommunication',
  'Metals',
  'Metals & Mining',
  'Mining & Commodities',
  'Oil & Gas',
  'Real Estate',
  'SaaS',
  'Tech-Enabled Hardware',
  'Tech-Enabled Services',
  'Technology',
  'Technology & Software',
  'Transportation & Logistics',
  'Utilities',
] as const;
