export const LOAN_TYPE_OPTIONS = [
  'ABL',
  'AR',
  'AR Inventory',
  'Bridge Financing',
  'CAPEX',
  'Equipment Financing',
  'Factoring',
  'Full ABL',
  'Growth Capital',
  'Inventory',
  'MCA',
  'PO',
  'Revenue-Based Financing',
  'Revolver',
  'SBA Loan',
  'Sale Leaseback',
  'Senior Debt',
  'Sub Debt',
  'Term Loan',
] as const;
