import type { CsvSchema } from '@/utils/entityCsv';

export const DEAL_CSV: CsvSchema = {
  requiredKey: 'company',
  fields: [
    { key: 'id', header: 'Record ID', kind: 'text', readOnly: true },
    { key: 'company', header: 'Company', kind: 'text', aliases: ['company name', 'deal', 'deal name', 'name', 'client'], example: 'Example Co' },
    { key: 'stage', header: 'Stage', kind: 'text', aliases: ['deal stage'], example: 'Initial Review' },
    { key: 'status', header: 'Status', kind: 'text' },
    { key: 'value', header: 'Deal Value ($)', kind: 'number', aliases: ['value', 'deal size', 'amount', 'deal value', 'size'], example: '5000000' },
    { key: 'deal_type', header: 'Deal Type', kind: 'text', aliases: ['type'] },
    { key: 'engagement_type', header: 'Engagement Type', kind: 'text' },
    { key: 'exclusivity', header: 'Exclusivity', kind: 'text' },
    { key: 'deal_owner', header: 'Deal Owner', kind: 'text', aliases: ['owner'] },
    { key: 'manager', header: 'Manager', kind: 'text' },
    { key: 'analyst', header: 'Analyst', kind: 'text' },
    { key: 'owned_by', header: 'Owned By', kind: 'text' },
    { key: 'contact', header: 'Contact Name', kind: 'text', aliases: ['contact', 'primary contact'], example: 'Jane Smith' },
    { key: 'contact_email', header: 'Contact Email', kind: 'text', aliases: ['email'], example: 'jane@example.com' },
    { key: 'contact_title', header: 'Contact Title', kind: 'text' },
    { key: 'contact_info', header: 'Contact Info', kind: 'text', aliases: ['phone'] },
    { key: 'company_url', header: 'Company URL', kind: 'text', aliases: ['website', 'url', 'domain'], example: 'https://example.com' },
    { key: 'business_model', header: 'Business Model', kind: 'text' },
    { key: 'referred_by', header: 'Referred By', kind: 'text' },
    { key: 'referral_source', header: 'Referral Source', kind: 'text' },
    { key: 'lead_source', header: 'Lead Source', kind: 'text' },
    { key: 'sourced_via', header: 'Sourced Via', kind: 'text' },
    { key: 'opportunity_type', header: 'Opportunity Type', kind: 'text' },
    { key: 'icp_category', header: 'ICP Category', kind: 'text' },
    { key: 'prospect_type', header: 'Prospect Type', kind: 'text' },
    { key: 'fee_type', header: 'Fee Type', kind: 'text' },
    { key: 'retainer_fee', header: 'Retainer Fee ($)', kind: 'number' },
    { key: 'milestone_fee', header: 'Milestone Fee ($)', kind: 'number' },
    { key: 'success_fee_percent', header: 'Success Fee (%)', kind: 'number' },
    { key: 'total_fee', header: 'Total Fee ($)', kind: 'number' },
    { key: 'mrr', header: 'MRR ($)', kind: 'number' },
    { key: 'one_time_revenue', header: 'One-Time Revenue ($)', kind: 'number' },
    { key: 'pricing', header: 'Pricing', kind: 'text' },
    { key: 'services_offered', header: 'Services Offered', kind: 'array' },
    { key: 'closing_date', header: 'Closing Date', kind: 'date' },
    { key: 'projected_close_date', header: 'Projected Close Date', kind: 'date' },
    { key: 'contract_start_date', header: 'Contract Start Date', kind: 'date' },
    { key: 'contract_end_date', header: 'Contract End Date', kind: 'date' },
    { key: 'next_step', header: 'Next Step', kind: 'text' },
    { key: 'next_step_date', header: 'Next Step Date', kind: 'date' },
    { key: 'outcome', header: 'Outcome', kind: 'text' },
    { key: 'lost_reason', header: 'Lost Reason', kind: 'text' },
    { key: 'dm_present', header: 'Decision Maker Present', kind: 'text' },
    { key: 'dm_name', header: 'Decision Maker Name', kind: 'text' },
    { key: 'pain_points_confirmed', header: 'Pain Points', kind: 'text' },
    { key: 'objections_raised', header: 'Objections', kind: 'text' },
    { key: 'competitors_mentioned', header: 'Competitors', kind: 'text' },
    { key: 'key_signal', header: 'Key Signal', kind: 'text' },
    { key: 'on_hold', header: 'On Hold', kind: 'boolean' },
    { key: 'is_flagged', header: 'Flagged', kind: 'boolean' },
    { key: 'flag_notes', header: 'Flag Notes', kind: 'text' },
    { key: 'tags', header: 'Tags', kind: 'array' },
    { key: 'narrative', header: 'Narrative', kind: 'text' },
    { key: 'notes', header: 'Status Note', kind: 'text', aliases: ['notes', 'status', 'status notes'] },
    { key: 'created_at', header: 'Created', kind: 'text', readOnly: true },
    { key: 'updated_at', header: 'Last Updated', kind: 'text', readOnly: true },
  ],
};

export const CONTACT_COMPANY_NAME = '__company_name__';

export const CONTACT_CSV: CsvSchema = {
  requiredKey: 'email',
  fields: [
    { key: 'id', header: 'Record ID', kind: 'text', readOnly: true },
    { key: 'first_name', header: 'First Name', kind: 'text', aliases: ['firstname', 'given name'], example: 'Jane' },
    { key: 'last_name', header: 'Last Name', kind: 'text', aliases: ['lastname', 'surname'], example: 'Smith' },
    { key: 'full_name', header: 'Full Name', kind: 'text', aliases: ['name', 'contact name'] },
    { key: 'email', header: 'Email', kind: 'text', aliases: ['email address', 'e-mail', 'primary email'], example: 'jane@example.com' },
    { key: CONTACT_COMPANY_NAME, header: 'Company Name', kind: 'text', aliases: ['company', 'account', 'organization', 'employer'], example: 'Example Co' },
    { key: 'job_title', header: 'Job Title', kind: 'text', aliases: ['title', 'role', 'position'], example: 'CFO' },
    { key: 'department', header: 'Department', kind: 'text' },
    { key: 'seniority', header: 'Seniority', kind: 'text' },
    { key: 'phone_work', header: 'Phone Number', kind: 'text', aliases: ['phone', 'work phone', 'office phone'] },
    { key: 'phone_mobile', header: 'Mobile Phone Number', kind: 'text', aliases: ['mobile', 'cell', 'mobile phone'] },
    { key: 'phone_other', header: 'Other Phone', kind: 'text' },
    { key: 'linkedin_url', header: 'LinkedIn URL', kind: 'text', aliases: ['linkedin'] },
    { key: 'website_url', header: 'Website', kind: 'text', aliases: ['url'] },
    { key: 'city', header: 'City', kind: 'text' },
    { key: 'state_region', header: 'State/Region', kind: 'text', aliases: ['state', 'region', 'province'] },
    { key: 'country', header: 'Country', kind: 'text' },
    { key: 'geography', header: 'Geography', kind: 'text' },
    { key: 'timezone', header: 'Time Zone', kind: 'text' },
    { key: 'contact_type', header: 'Contact Type', kind: 'text', aliases: ['type'] },
    { key: 'lead_status', header: 'Lead Status', kind: 'text' },
    { key: 'lifecycle_stage', header: 'Lifecycle Stage', kind: 'text' },
    { key: 'status', header: 'Status', kind: 'text' },
    { key: 'buying_role', header: 'Buying Role', kind: 'text' },
    { key: 'industry', header: 'Industry', kind: 'text', aliases: ['sector'] },
    { key: 'lead_source', header: 'Lead Source', kind: 'text', aliases: ['source'] },
    { key: 'campaign', header: 'Campaign', kind: 'text' },
    { key: 'preferred_channel', header: 'Preferred Channel', kind: 'text' },
    { key: 'email_opt_in', header: 'Email Opt In', kind: 'boolean' },
    { key: 'opted_out_one_to_one', header: 'Opted Out of One-to-One Email', kind: 'boolean', aliases: ['opted out', 'unsubscribed'] },
    { key: 'contact_score', header: 'Contact Score', kind: 'number' },
    { key: 'referral_fee', header: 'Referral Fee', kind: 'text' },
    { key: 'referral_agreement_on_file', header: 'Referral Agreement on File', kind: 'boolean' },
    { key: 'w9_on_file', header: 'W9 on File', kind: 'boolean' },
    { key: 'additional_emails', header: 'Additional Emails', kind: 'array' },
    { key: 'tags', header: 'Tags', kind: 'array' },
    { key: 'description', header: 'Notes', kind: 'text', aliases: ['description', 'about'] },
    { key: 'last_contacted_date', header: 'Last Contacted', kind: 'date' },
    { key: 'created_at', header: 'Created', kind: 'text', readOnly: true },
  ],
};

export const COMPANY_CSV: CsvSchema = {
  requiredKey: 'name',
  fields: [
    { key: 'id', header: 'Record ID', kind: 'text', readOnly: true },
    { key: 'name', header: 'Company Name', kind: 'text', aliases: ['company', 'name', 'account', 'account name', 'organization'], example: 'Example Co' },
    { key: 'domain', header: 'Domain', kind: 'text', aliases: ['company domain name', 'website domain'], example: 'example.com' },
    { key: 'website_url', header: 'Website', kind: 'text', aliases: ['url', 'site', 'website url'] },
    { key: 'additional_domains', header: 'Additional Domains', kind: 'array' },
    { key: 'industry', header: 'Industry', kind: 'text', aliases: ['sector'], example: 'SaaS' },
    { key: 'sub_industry', header: 'Sub-Industry', kind: 'text' },
    { key: 'segment', header: 'Segment', kind: 'text' },
    { key: 'company_type', header: 'Company Type', kind: 'text', aliases: ['type'] },
    { key: 'status', header: 'Status', kind: 'text' },
    { key: 'lifecycle_stage', header: 'Lifecycle Stage', kind: 'text', aliases: ['stage'] },
    { key: 'customer_tier', header: 'Customer Tier', kind: 'text', aliases: ['tier'] },
    { key: 'employee_count', header: 'Employee Count', kind: 'integer', aliases: ['employees', 'headcount', 'number of employees'] },
    { key: 'employee_range', header: 'Employee Range', kind: 'text', aliases: ['size'] },
    { key: 'annual_revenue', header: 'Annual Revenue ($)', kind: 'number', aliases: ['revenue', 'annual revenue'] },
    { key: 'revenue_band', header: 'Revenue Band', kind: 'text' },
    { key: 'arr', header: 'ARR ($)', kind: 'number' },
    { key: 'mrr', header: 'MRR ($)', kind: 'number' },
    { key: 'total_contract_value', header: 'Total Contract Value ($)', kind: 'number' },
    { key: 'year_founded', header: 'Year Founded', kind: 'integer', aliases: ['founded', 'founded year'] },
    { key: 'financing_status', header: 'Financing Status', kind: 'text', aliases: ['company financing status', 'funding status'] },
    { key: 'hq_address', header: 'HQ Address', kind: 'text' },
    { key: 'address', header: 'Address', kind: 'text' },
    { key: 'hq_city', header: 'City', kind: 'text' },
    { key: 'hq_state', header: 'State', kind: 'text', aliases: ['state region'] },
    { key: 'hq_postal_code', header: 'Postal Code', kind: 'text', aliases: ['zip', 'zip code'] },
    { key: 'hq_country', header: 'Country', kind: 'text', aliases: ['country region'] },
    { key: 'regions_served', header: 'Regions Served', kind: 'array' },
    { key: 'phone', header: 'Phone', kind: 'text' },
    { key: 'main_contact_email', header: 'Main Email', kind: 'text', aliases: ['email'] },
    { key: 'linkedin_url', header: 'LinkedIn URL', kind: 'text', aliases: ['linkedin'] },
    { key: 'twitter_url', header: 'Twitter URL', kind: 'text' },
    { key: 'key_products', header: 'Key Products', kind: 'array' },
    { key: 'contract_start_date', header: 'Contract Start Date', kind: 'date' },
    { key: 'contract_end_date', header: 'Contract End Date', kind: 'date' },
    { key: 'renewal_date', header: 'Renewal Date', kind: 'date' },
    { key: 'tags', header: 'Tags', kind: 'array' },
    { key: 'description', header: 'Description', kind: 'text' },
    { key: 'notes', header: 'Notes', kind: 'text' },
    { key: 'created_at', header: 'Created', kind: 'text', readOnly: true },
  ],
};

/** Physical columns to select for export (skips virtual keys). */
export const selectColumns = (schema: CsvSchema) =>
  schema.fields.map(f => f.key).filter(k => !k.startsWith('__')).join(', ');
