import { useState, useMemo } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { FileDown, CalendarIcon } from 'lucide-react';
import { format, subDays } from 'date-fns';
import { cn } from '@/lib/utils';
import { useAuth } from '@/contexts/AuthContext';
import { useCompany } from '@/hooks/useCompany';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

type TimePeriod = '7d' | '30d' | '90d';

interface InsightItem {
  id: string;
  type: string;
  summary: string;
  userName?: string;
  timestamp: string;
}

interface Props {
  open: boolean;
  onClose: () => void;
  insights: InsightItem[];
  period: TimePeriod;
}

const SECTIONS = [
  { key: 'pipeline', label: 'Pipeline Movements' },
  { key: 'deals', label: 'Deals Referred' },
  { key: 'memos', label: 'Partner Memo Updates' },
  { key: 'leaderboard', label: 'Leaderboard Highlights' },
  { key: 'insights', label: 'All Insights Feed' },
] as const;

type SectionKey = typeof SECTIONS[number]['key'];

const TYPE_MAP: Record<string, SectionKey> = {
  stage_move: 'pipeline',
  new_deal: 'deals',
  memo_update: 'memos',
  new_partner: 'insights',
  stale_alert: 'insights',
};

export function PartnerReportBuilder({ open, onClose, insights, period }: Props) {
  const { user } = useAuth();
  const { company } = useCompany();
  const periodDays = period === '7d' ? 7 : period === '30d' ? 30 : 90;

  const [dateFrom, setDateFrom] = useState<Date>(subDays(new Date(), periodDays));
  const [dateTo, setDateTo] = useState<Date>(new Date());
  const [enabledSections, setEnabledSections] = useState<Set<SectionKey>>(
    new Set(SECTIONS.map(s => s.key))
  );
  const [execSummary, setExecSummary] = useState('');
  const [commentary, setCommentary] = useState<Record<SectionKey, string>>({
    pipeline: '', deals: '', memos: '', leaderboard: '', insights: '',
  });
  const [exporting, setExporting] = useState(false);

  const toggleSection = (key: SectionKey) => {
    setEnabledSections(prev => {
      const next = new Set(prev);
      next.has(key) ? next.delete(key) : next.add(key);
      return next;
    });
  };

  const filteredInsights = useMemo(() => {
    const from = dateFrom.toISOString();
    const to = dateTo.toISOString();
    return insights.filter(i => i.timestamp >= from && i.timestamp <= to);
  }, [insights, dateFrom, dateTo]);

  const groupedInsights = useMemo(() => {
    const groups: Record<SectionKey, InsightItem[]> = {
      pipeline: [], deals: [], memos: [], leaderboard: [], insights: [],
    };
    for (const i of filteredInsights) {
      const section = TYPE_MAP[i.type] || 'insights';
      groups[section].push(i);
    }
    return groups;
  }, [filteredInsights]);

  const exportPDF = async () => {
    setExporting(true);
    try {
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pageW = doc.internal.pageSize.getWidth();
      const pageH = doc.internal.pageSize.getHeight();
      const margin = 20;
      const contentW = pageW - margin * 2;

      // Cover page
      doc.setFillColor(15, 23, 42); // slate-900
      doc.rect(0, 0, pageW, pageH, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(28);
      doc.text('Partner Insights Report', margin, 80);
      doc.setFontSize(14);
      doc.setTextColor(148, 163, 184);
      doc.text(`${format(dateFrom, 'MMM d, yyyy')} — ${format(dateTo, 'MMM d, yyyy')}`, margin, 95);
      doc.setFontSize(12);
      doc.text(company?.name || '', margin, 115);
      doc.text(`Generated by ${(user as any)?.user_metadata?.display_name || user?.email || 'User'}`, margin, 128);
      doc.text(`Generated on ${format(new Date(), 'MMMM d, yyyy')}`, margin, 141);

      // Content pages
      doc.addPage();
      doc.setFillColor(255, 255, 255);
      doc.rect(0, 0, pageW, pageH, 'F');
      let y = margin;

      const addHeading = (text: string) => {
        if (y > pageH - 40) { doc.addPage(); y = margin; }
        doc.setFontSize(16);
        doc.setTextColor(15, 23, 42);
        doc.text(text, margin, y);
        y += 3;
        doc.setDrawColor(59, 130, 246);
        doc.setLineWidth(0.5);
        doc.line(margin, y, margin + contentW, y);
        y += 8;
      };

      const addParagraph = (text: string) => {
        if (!text.trim()) return;
        doc.setFontSize(10);
        doc.setTextColor(51, 65, 85);
        const lines = doc.splitTextToSize(text, contentW);
        for (const line of lines) {
          if (y > pageH - 15) { doc.addPage(); y = margin; }
          doc.text(line, margin, y);
          y += 5;
        }
        y += 4;
      };

      // Executive Summary
      if (execSummary.trim()) {
        addHeading('Executive Summary');
        addParagraph(execSummary);
      }

      // Sections
      for (const section of SECTIONS) {
        if (!enabledSections.has(section.key)) continue;
        const items = groupedInsights[section.key];

        addHeading(section.label);

        if (items.length > 0) {
          autoTable(doc, {
            startY: y,
            margin: { left: margin, right: margin },
            head: [['Activity', 'By', 'Date']],
            body: items.map(i => [
              i.summary,
              i.userName || '—',
              format(new Date(i.timestamp), 'MMM d, yyyy'),
            ]),
            headStyles: { fillColor: [59, 130, 246], textColor: 255, fontSize: 9 },
            bodyStyles: { fontSize: 9, textColor: [51, 65, 85] },
            alternateRowStyles: { fillColor: [241, 245, 249] },
            theme: 'striped',
          });
          y = (doc as any).lastAutoTable.finalY + 6;
        } else {
          doc.setFontSize(10);
          doc.setTextColor(148, 163, 184);
          doc.text('No data for this period.', margin, y);
          y += 8;
        }

        // Commentary
        const note = commentary[section.key];
        if (note?.trim()) {
          addParagraph(note);
        }
      }

      doc.save(`Partner_Insights_Report_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
    } finally {
      setExporting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={v => !v && onClose()}>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Draft Partner Insights Report</DialogTitle>
        </DialogHeader>

        <div className="space-y-6 mt-2">
          {/* Date range */}
          <div className="flex flex-wrap gap-4 items-end">
            <div className="space-y-1">
              <Label className="text-xs">From</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" size="sm" className={cn('w-[160px] justify-start text-left font-normal', !dateFrom && 'text-muted-foreground')}>
                    <CalendarIcon className="mr-2 h-3.5 w-3.5" />
                    {format(dateFrom, 'MMM d, yyyy')}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar mode="single" selected={dateFrom} onSelect={d => d && setDateFrom(d)} className="p-3 pointer-events-auto" />
                </PopoverContent>
              </Popover>
            </div>
            <div className="space-y-1">
              <Label className="text-xs">To</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" size="sm" className={cn('w-[160px] justify-start text-left font-normal', !dateTo && 'text-muted-foreground')}>
                    <CalendarIcon className="mr-2 h-3.5 w-3.5" />
                    {format(dateTo, 'MMM d, yyyy')}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar mode="single" selected={dateTo} onSelect={d => d && setDateTo(d)} className="p-3 pointer-events-auto" />
                </PopoverContent>
              </Popover>
            </div>
          </div>

          {/* Sections to include */}
          <div>
            <Label className="text-xs mb-2 block">Include Sections</Label>
            <div className="flex flex-wrap gap-3">
              {SECTIONS.map(s => (
                <label key={s.key} className="flex items-center gap-2 text-sm cursor-pointer">
                  <Checkbox checked={enabledSections.has(s.key)} onCheckedChange={() => toggleSection(s.key)} />
                  {s.label}
                </label>
              ))}
            </div>
          </div>

          {/* Executive Summary */}
          <div>
            <Label className="text-xs mb-1 block">Executive Summary</Label>
            <Textarea
              placeholder="Write an overall narrative for this report..."
              value={execSummary}
              onChange={e => setExecSummary(e.target.value)}
              className="min-h-[80px]"
            />
          </div>

          {/* Section previews with commentary */}
          {SECTIONS.filter(s => enabledSections.has(s.key)).map(section => {
            const items = groupedInsights[section.key];
            return (
              <div key={section.key} className="rounded-lg border border-border bg-muted/20 p-4 space-y-3">
                <h4 className="text-sm font-semibold">{section.label} <span className="text-muted-foreground font-normal">({items.length})</span></h4>
                {items.length > 0 ? (
                  <div className="max-h-[150px] overflow-y-auto space-y-1 text-xs text-muted-foreground">
                    {items.slice(0, 15).map(i => (
                      <p key={i.id}>• {i.summary} {i.userName ? `— ${i.userName}` : ''} · {format(new Date(i.timestamp), 'MMM d')}</p>
                    ))}
                    {items.length > 15 && <p className="italic">...and {items.length - 15} more</p>}
                  </div>
                ) : (
                  <p className="text-xs text-muted-foreground italic">No data for this period.</p>
                )}
                <Textarea
                  placeholder={`Add commentary for ${section.label}...`}
                  value={commentary[section.key]}
                  onChange={e => setCommentary(prev => ({ ...prev, [section.key]: e.target.value }))}
                  className="min-h-[60px] text-sm"
                />
              </div>
            );
          })}

          {/* Export button */}
          <div className="flex justify-end">
            <Button onClick={exportPDF} disabled={exporting} className="gap-2">
              <FileDown className="h-4 w-4" />
              {exporting ? 'Generating...' : 'Export to PDF'}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
