// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-deals.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.23.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  const token = ctx.getToken();
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
  }
  return null;
}
function textResult(payload, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    ...structured ? { structuredContent: structured } : {}
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
async function assertDealAccess(sb, ctx, deal_id, toolName) {
  const caller_uid = ctx.getUserId?.() ?? null;
  const { data: deal, error } = await sb.from("deals").select("id, company, user_id, company_id").eq("id", deal_id).maybeSingle();
  if (error) {
    console.error(`[${toolName}] deal access probe error`, {
      deal_id,
      caller_uid,
      message: error.message
    });
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            { error: "forbidden", reason: error.message, deal_id },
            null,
            2
          )
        }
      ],
      structuredContent: { error: "forbidden", reason: error.message, deal_id },
      isError: true
    };
  }
  if (!deal) {
    console.warn(`[${toolName}] rls-denied`, {
      deal_id,
      caller_uid,
      deal_visible: false
    });
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              error: "forbidden",
              reason: "caller lacks RLS access to this deal's company",
              deal_id
            },
            null,
            2
          )
        }
      ],
      structuredContent: {
        error: "forbidden",
        reason: "caller lacks RLS access to this deal's company",
        deal_id
      },
      isError: true
    };
  }
  console.log(`[${toolName}] deal access ok`, {
    deal_id,
    caller_uid,
    deal_company_id: deal.company_id ?? null,
    deal_owner_uid: deal.user_id ?? null
  });
  return null;
}

// src/lib/mcp/tools/list-deals.ts
var list_deals_default = defineTool({
  name: "list_deals",
  title: "List deals",
  description: "List the naitive deals the signed-in user can see, returning full row records (not just a count). Optionally filter by stage, pipeline_id, a text query against the company/deal name, or a created_at/closing_date window (use created_from/created_to for questions like 'deals created in August'). Returns id, company, stage, value, closing_date, created_at, pipeline_id, deal_owner, manager, status, updated_at.",
  inputSchema: {
    query: z.string().trim().min(1).max(200).optional().describe("Substring search across the company / deal name."),
    stage: z.string().trim().min(1).max(100).optional().describe("Exact stage id (e.g. 'nda-needs-list', 'on-deck')."),
    pipeline_id: z.string().uuid().optional(),
    created_from: z.string().trim().max(40).optional().describe("ISO date/timestamp lower bound on created_at (inclusive)."),
    created_to: z.string().trim().max(40).optional().describe("ISO date/timestamp upper bound on created_at (exclusive)."),
    closing_from: z.string().trim().max(40).optional().describe("ISO date lower bound on closing_date (inclusive)."),
    closing_to: z.string().trim().max(40).optional().describe("ISO date upper bound on closing_date (exclusive)."),
    limit: z.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, stage, pipeline_id, created_from, created_to, closing_from, closing_to, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    let q = sb.from("deals").select(
      "id, company, stage, status, value, closing_date, created_at, pipeline_id, deal_owner, manager, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit);
    if (stage) q = q.eq("stage", stage);
    if (pipeline_id) q = q.eq("pipeline_id", pipeline_id);
    if (query) q = q.ilike("company", `%${query}%`);
    if (created_from) q = q.gte("created_at", created_from);
    if (created_to) q = q.lt("created_at", created_to);
    if (closing_from) q = q.gte("closing_date", closing_from);
    if (closing_to) q = q.lt("closing_date", closing_to);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    const rows = data ?? [];
    return textResult(rows, { count: rows.length, deals: rows });
  }
});

// src/lib/mcp/tools/get-deal.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.23.0";
var get_deal_default = defineTool2({
  name: "get_deal",
  title: "Get deal",
  description: "Fetch a single deal by id with its full record, plus recent status notes, tasks, and attached lenders.",
  inputSchema: {
    deal_id: z2.string().uuid(),
    include_tasks: z2.boolean().default(true),
    include_lenders: z2.boolean().default(true)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id, include_tasks, include_lenders }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const denied = await assertDealAccess(sb, ctx, deal_id, "get_deal");
    if (denied) return denied;
    const { data: deal, error } = await sb.from("deals").select("*").eq("id", deal_id).maybeSingle();
    if (error) return errorResult(error.message);
    if (!deal) return errorResult("Deal not found or you do not have access.");
    const [tasksRes, lendersRes] = await Promise.all([
      include_tasks ? sb.from("tasks").select("id, title, status, due_date, priority, assigned_to, created_at").eq("deal_id", deal_id).order("created_at", { ascending: false }).limit(50) : Promise.resolve({ data: null, error: null }),
      include_lenders ? sb.from("deal_lenders").select("id, lender_id, status, stage, updated_at").eq("deal_id", deal_id).order("updated_at", { ascending: false }).limit(200) : Promise.resolve({ data: null, error: null })
    ]);
    return textResult({
      deal,
      tasks: tasksRes.data ?? [],
      lenders: lendersRes.data ?? []
    });
  }
});

// src/lib/mcp/tools/update-deal.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.23.0";
var update_deal_default = defineTool3({
  name: "update_deal",
  title: "Update deal",
  description: "Update a deal's stage and/or high-level fields (value, closing_date, deal_owner, manager, narrative, is_flagged, flag_notes). Only fields you pass are changed. Returns the updated deal row.",
  inputSchema: {
    deal_id: z3.string().uuid(),
    stage: z3.string().trim().min(1).max(100).optional(),
    value: z3.number().nonnegative().optional(),
    closing_date: z3.string().nullable().optional().describe("ISO date, or null to clear."),
    deal_owner: z3.string().trim().max(200).optional(),
    manager: z3.string().trim().max(200).optional(),
    narrative: z3.string().max(2e4).optional(),
    is_flagged: z3.boolean().optional(),
    flag_notes: z3.string().max(2e3).nullable().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const { deal_id, ...rest } = input;
    const patch = {};
    for (const [k, v] of Object.entries(rest)) if (v !== void 0) patch[k] = v;
    if (Object.keys(patch).length === 0) return errorResult("No fields to update.");
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("deals").update(patch).eq("id", deal_id).select().maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Deal not found or you do not have permission to update it.");
    return textResult(data, { deal_id });
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.23.0";
var list_tasks_default = defineTool4({
  name: "list_tasks",
  title: "List tasks",
  description: "List tasks the signed-in user can see, optionally filtered by deal, status, or assignee (assigned_to user id). Returns full row records.",
  inputSchema: {
    deal_id: z4.string().uuid().optional(),
    status: z4.enum(["not_started", "pending", "in_progress", "completed", "complete"]).optional(),
    assigned_to: z4.string().uuid().optional().describe("User id the task is assigned to."),
    query: z4.string().trim().max(200).optional(),
    limit: z4.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id, status, assigned_to, query, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    let q = sb.from("tasks").select(
      "id, title, description, status, priority, due_date, completed_at, assigned_to, assigned_by, task_type, deal_id, contact_id, crm_company_id, company_id, created_at"
    ).order("due_date", { ascending: true, nullsFirst: false }).limit(limit);
    if (deal_id) q = q.eq("deal_id", deal_id);
    if (status) q = q.eq("status", status);
    if (assigned_to) q = q.eq("assigned_to", assigned_to);
    if (query) q = q.ilike("title", `%${query}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    const rows = data ?? [];
    return textResult(rows, { count: rows.length, tasks: rows });
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.23.0";
var create_task_default = defineTool5({
  name: "create_task",
  title: "Create task",
  description: "Create a task, optionally tied to a deal, contact, or company. Returns the created row.",
  inputSchema: {
    title: z5.string().trim().min(1).max(500),
    description: z5.string().max(1e4).optional(),
    due_date: z5.string().nullable().optional().describe("ISO date."),
    priority: z5.enum(["low", "medium", "high", "urgent"]).optional(),
    assigned_to: z5.string().uuid().optional().describe("User id to assign the task to."),
    deal_id: z5.string().uuid().optional(),
    contact_id: z5.string().uuid().optional(),
    company_id: z5.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const row = {
      title: input.title,
      status: "not_started",
      created_by: ctx.getUserId()
    };
    for (const k of ["description", "due_date", "priority", "assigned_to", "deal_id", "contact_id", "company_id"]) {
      if (input[k] !== void 0) row[k] = input[k];
    }
    const { data, error } = await sb.from("tasks").insert(row).select().maybeSingle();
    if (error) return errorResult(error.message);
    return textResult(data, { task_id: data?.id });
  }
});

// src/lib/mcp/tools/complete-task.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^3.23.0";
var complete_task_default = defineTool6({
  name: "complete_task",
  title: "Complete task",
  description: "Mark a task as completed.",
  inputSchema: { task_id: z6.string().uuid() },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ task_id }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("tasks").update({ status: "completed", completed_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", task_id).select().maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Task not found or not accessible.");
    return textResult(data);
  }
});

// src/lib/mcp/tools/search-contacts.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z7 } from "npm:zod@^3.23.0";
var search_contacts_default = defineTool7({
  name: "search_contacts",
  title: "Search contacts",
  description: "Search CRM contacts by name, email, or domain. Returns id, name, email, phone, domain, title, company.",
  inputSchema: {
    query: z7.string().trim().min(1).max(200),
    limit: z7.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const like = `%${query}%`;
    const { data, error } = await sb.from("contacts").select("id, first_name, last_name, email, phone, website_url, job_title, company, created_at").or(`first_name.ilike.${like},last_name.ilike.${like},email.ilike.${like},website_url.ilike.${like},company.ilike.${like}`).limit(limit);
    if (error) return errorResult(error.message);
    return textResult(data ?? [], { count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/search-companies.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z8 } from "npm:zod@^3.23.0";
var search_companies_default = defineTool8({
  name: "search_companies",
  title: "Search companies",
  description: "Search CRM companies by name, domain, or website. Returns full row records.",
  inputSchema: {
    query: z8.string().trim().min(1).max(200),
    limit: z8.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const like = `%${query}%`;
    const { data, error } = await sb.from("crm_companies").select(
      "id, name, domain, website_url, industry, company_type, status, hq_city, hq_state, hq_country, created_at"
    ).or(`name.ilike.${like},domain.ilike.${like},website_url.ilike.${like}`).limit(limit);
    if (error) return errorResult(error.message);
    const rows = data ?? [];
    return textResult(rows, { count: rows.length, companies: rows });
  }
});

// src/lib/mcp/tools/create-contact.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z9 } from "npm:zod@^3.23.0";
var create_contact_default = defineTool9({
  name: "create_contact",
  title: "Create contact",
  description: "Create a CRM contact. Provide at minimum an email or first_name/last_name.",
  inputSchema: {
    first_name: z9.string().trim().max(200).optional(),
    last_name: z9.string().trim().max(200).optional(),
    email: z9.string().trim().email().optional(),
    phone: z9.string().trim().max(50).optional(),
    website_url: z9.string().trim().max(500).optional().describe("Contact domain (matches to company)."),
    job_title: z9.string().trim().max(200).optional(),
    company: z9.string().trim().max(200).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    if (!input.email && !input.first_name && !input.last_name) {
      return errorResult("Provide at least email or first_name/last_name.");
    }
    const sb = supabaseForUser(ctx);
    const row = { created_by: ctx.getUserId() };
    for (const [k, v] of Object.entries(input)) if (v !== void 0) row[k] = v;
    const { data, error } = await sb.from("contacts").insert(row).select("id, first_name, last_name, email, website_url").maybeSingle();
    if (error) return errorResult(error.message);
    return textResult(data, { contact_id: data?.id });
  }
});

// src/lib/mcp/tools/create-company.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z10 } from "npm:zod@^3.23.0";
var create_company_default = defineTool10({
  name: "create_company",
  title: "Create company",
  description: "Create a CRM company record.",
  inputSchema: {
    name: z10.string().trim().min(1).max(300),
    website_url: z10.string().trim().max(500).optional(),
    industry: z10.string().trim().max(200).optional(),
    city: z10.string().trim().max(200).optional(),
    state: z10.string().trim().max(200).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const row = { created_by: ctx.getUserId() };
    for (const [k, v] of Object.entries(input)) if (v !== void 0) row[k] = v;
    const { data, error } = await sb.from("crm_companies").insert(row).select("id, name, website_url").maybeSingle();
    if (error) return errorResult(error.message);
    return textResult(data, { company_id: data?.id });
  }
});

// src/lib/mcp/tools/search-lenders.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z11 } from "npm:zod@^3.23.0";
var search_lenders_default = defineTool11({
  name: "search_lenders",
  title: "Search funding sources / lenders",
  description: "Search the master lender directory by name, product, or geography. Optionally filter by deal_size (returns lenders whose min_deal_size <= size <= max_deal_size).",
  inputSchema: {
    query: z11.string().trim().max(200).optional(),
    deal_size: z11.number().nonnegative().optional(),
    limit: z11.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, deal_size, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    let q = sb.from("master_lenders").select("id, name, lender_type, tier, min_deal_size, max_deal_size, loan_types, geographies, website").limit(limit);
    if (query) q = q.ilike("name", `%${query}%`);
    if (deal_size !== void 0) q = q.lte("min_deal_size", deal_size).gte("max_deal_size", deal_size);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(data ?? [], { count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/add-lender-to-deal.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z12 } from "npm:zod@^3.23.0";
var add_lender_to_deal_default = defineTool12({
  name: "add_lender_to_deal",
  title: "Add lender to deal",
  description: "Attach a funding source / lender to a deal. Per project rule, new lenders default to the 'On Deck' stage.",
  inputSchema: {
    deal_id: z12.string().uuid(),
    lender_id: z12.string().uuid(),
    stage: z12.string().trim().max(100).default("on-deck"),
    status: z12.string().trim().max(100).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ deal_id, lender_id, stage, status }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const row = { deal_id, lender_id, stage, created_by: ctx.getUserId() };
    if (status) row.status = status;
    const { data, error } = await sb.from("deal_lenders").insert(row).select().maybeSingle();
    if (error) return errorResult(error.message);
    return textResult(data, { deal_lender_id: data?.id });
  }
});

// src/lib/mcp/tools/search-deal-notes.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z13 } from "npm:zod@^3.23.0";
var search_deal_notes_default = defineTool13({
  name: "search_deal_notes",
  title: "Search deal notes",
  description: "Search notes attached to a specific deal (deal space notes). Optionally filter by a text query against title/content/tags. Returns id, title, content, folder, tags, is_pinned, user_id, updated_at.",
  inputSchema: {
    deal_id: z13.string().uuid(),
    query: z13.string().trim().min(1).max(200).optional(),
    limit: z13.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id, query, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const denied = await assertDealAccess(sb, ctx, deal_id, "search_deal_notes");
    if (denied) return denied;
    let q = sb.from("deal_space_notes").select("id, deal_id, title, content, folder, tags, is_pinned, user_id, created_at, updated_at").eq("deal_id", deal_id).order("updated_at", { ascending: false }).limit(limit);
    if (query) {
      const like = `%${query}%`;
      q = q.or(`title.ilike.${like},content.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(data ?? [], { count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/list-deal-activity.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z14 } from "npm:zod@^3.23.0";
var list_deal_activity_default = defineTool14({
  name: "list_deal_activity",
  title: "List deal activity",
  description: "List recent activity/timeline events for a deal \u2014 stage changes, field updates, emails, calls, notes, and other logged actions. Combines deal_activity (structured field changes) with activity_logs (rich events including emails). Returns items ordered by most recent first.",
  inputSchema: {
    deal_id: z14.string().uuid(),
    activity_type: z14.string().trim().min(1).max(60).optional().describe("Optional activity_type filter for activity_logs (e.g. 'email', 'call', 'note', 'stage_change')."),
    limit: z14.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id, activity_type, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const denied = await assertDealAccess(sb, ctx, deal_id, "list_deal_activity");
    if (denied) return denied;
    let logsQ = sb.from("activity_logs").select(
      "id, activity_type, description, user_display_name, direction, subject, from_address, to_addresses, sent_at, thread_id, provider, metadata, created_at"
    ).eq("deal_id", deal_id).order("created_at", { ascending: false }).limit(limit);
    if (activity_type) logsQ = logsQ.eq("activity_type", activity_type);
    const [logsRes, changesRes] = await Promise.all([
      logsQ,
      sb.from("deal_activity").select("id, source, action_type, before, after, user_id, created_at").eq("deal_id", deal_id).order("created_at", { ascending: false }).limit(limit)
    ]);
    if (logsRes.error) return errorResult(logsRes.error.message);
    if (changesRes.error) return errorResult(changesRes.error.message);
    return textResult({
      activity_logs: logsRes.data ?? [],
      field_changes: changesRes.data ?? []
    });
  }
});

// src/lib/mcp/tools/search-deal-documents.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z15 } from "npm:zod@^3.23.0";
var search_deal_documents_default = defineTool15({
  name: "search_deal_documents",
  title: "Search deal documents",
  description: "Search files/documents attached to a specific deal (virtual data room). Optionally filter by name, category, or a text query against name/source_subject/extracted_text. Returns id, name, category, size_bytes, content_type, source, source_subject, created_at.",
  inputSchema: {
    deal_id: z15.string().uuid(),
    query: z15.string().trim().min(1).max(200).optional(),
    category: z15.string().trim().min(1).max(100).optional(),
    limit: z15.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id, query, category, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const denied = await assertDealAccess(sb, ctx, deal_id, "search_deal_documents");
    if (denied) return denied;
    let q = sb.from("deal_attachments").select(
      "id, deal_id, name, category, size_bytes, content_type, source, source_subject, source_sender, extraction_status, created_at, user_id"
    ).eq("deal_id", deal_id).order("created_at", { ascending: false }).limit(limit);
    if (category) q = q.eq("category", category);
    if (query) {
      const like = `%${query}%`;
      q = q.or(`name.ilike.${like},source_subject.ilike.${like},extracted_text.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(data ?? [], { count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/get-deal-document.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z16 } from "npm:zod@^3.23.0";
var get_deal_document_default = defineTool16({
  name: "get_deal_document",
  title: "Get deal document",
  description: "Fetch a single deal document/attachment record by id, including extracted_text when available. Use search_deal_documents first to find the id.",
  inputSchema: {
    document_id: z16.string().uuid(),
    include_extracted_text: z16.boolean().default(true)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ document_id, include_extracted_text }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const cols = include_extracted_text ? "id, deal_id, name, category, size_bytes, content_type, file_path, source, source_email_id, source_thread_id, source_subject, source_sender, extraction_status, extraction_error, extracted_text, extracted_at, created_at, user_id" : "id, deal_id, name, category, size_bytes, content_type, file_path, source, source_email_id, source_thread_id, source_subject, source_sender, extraction_status, extraction_error, extracted_at, created_at, user_id";
    const { data, error } = await sb.from("deal_attachments").select(cols).eq("id", document_id).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Document not found or you do not have access.");
    return textResult(data);
  }
});

// src/lib/mcp/tools/search-deal-emails.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z17 } from "npm:zod@^3.23.0";
var search_deal_emails_default = defineTool17({
  name: "search_deal_emails",
  title: "Search deal emails",
  description: "Search email/communication history logged against a deal. Queries activity_logs where activity_type = 'email' for the deal, optionally filtered by a text query against subject, body, from, or to addresses. Returns subject, direction, from/to, sent_at, thread_id, and body snippet.",
  inputSchema: {
    deal_id: z17.string().uuid(),
    query: z17.string().trim().min(1).max(200).optional(),
    direction: z17.enum(["inbound", "outbound"]).optional(),
    limit: z17.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id, query, direction, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const denied = await assertDealAccess(sb, ctx, deal_id, "search_deal_emails");
    if (denied) return denied;
    let q = sb.from("activity_logs").select(
      "id, subject, body, direction, from_address, to_addresses, cc_addresses, sent_at, thread_id, message_id, provider, user_display_name, created_at"
    ).eq("deal_id", deal_id).eq("activity_type", "email").order("sent_at", { ascending: false, nullsFirst: false }).limit(limit);
    if (direction) q = q.eq("direction", direction);
    if (query) {
      const like = `%${query}%`;
      q = q.or(`subject.ilike.${like},body.ilike.${like},from_address.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(data ?? [], { count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/search-deal-recordings.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z18 } from "npm:zod@^3.23.0";
var search_deal_recordings_default = defineTool18({
  name: "search_deal_recordings",
  title: "Search deal meeting recordings",
  description: "List Claap meeting recordings and transcripts linked to a deal. Returns recording title, duration, recorder, thumbnail/url, and \u2014 when include_transcript is true \u2014 the transcript text and summary from claap_transcripts. Optional query filters recording title/summary/transcript.",
  inputSchema: {
    deal_id: z18.string().uuid(),
    query: z18.string().trim().min(1).max(200).optional(),
    include_transcript: z18.boolean().default(false),
    limit: z18.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id, query, include_transcript, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const denied = await assertDealAccess(sb, ctx, deal_id, "search_deal_recordings");
    if (denied) return denied;
    let recQ = sb.from("deal_claap_recordings").select(
      "id, recording_id, recording_title, recording_url, thumbnail_url, duration_seconds, recorder_name, recorder_email, linked_at, notes, created_at"
    ).eq("deal_id", deal_id).order("linked_at", { ascending: false, nullsFirst: false }).limit(limit);
    if (query) recQ = recQ.ilike("recording_title", `%${query}%`);
    const { data: recordings, error } = await recQ;
    if (error) return errorResult(error.message);
    let transcripts = [];
    if (include_transcript) {
      let tQ = sb.from("claap_transcripts").select("id, claap_meeting_id, transcript_text, summary, participants, duration_seconds, recorded_at, call_type").eq("deal_id", deal_id).order("recorded_at", { ascending: false, nullsFirst: false }).limit(limit);
      if (query) {
        const like = `%${query}%`;
        tQ = tQ.or(`transcript_text.ilike.${like},summary.ilike.${like}`);
      }
      const tRes = await tQ;
      if (tRes.error) return errorResult(tRes.error.message);
      transcripts = tRes.data ?? [];
    }
    return textResult({ recordings: recordings ?? [], transcripts });
  }
});

// src/lib/mcp/tools/list-deal-funding-sources.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z19 } from "npm:zod@^3.23.0";
var list_deal_funding_sources_default = defineTool19({
  name: "list_deal_funding_sources",
  title: "List deal funding sources / lenders",
  description: "List all funding sources (lenders) attached to a specific deal \u2014 the same records shown in the deal's Funding Sources tab. Returns each entry's stage/status, tracking bucket (active, on-deck, on-hold, passed, excluded), quote amount / rate / term, pass reason, and status-change timestamps (submitted, approved, declined, passed, on-deck, on-hold, excluded). Returns an empty list when the deal has no funding sources.",
  inputSchema: {
    deal_id: z19.string().uuid()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const denied = await assertDealAccess(sb, ctx, deal_id, "list_deal_funding_sources");
    if (denied) return denied;
    const { data, error } = await sb.from("deal_lenders").select(
      "id, deal_id, name, stage, substage, tracking_status, tags, score, notes, pass_reason, quote_amount, quote_rate, quote_term, submitted_at, approved_at, declined_at, passed_at, on_deck_at, on_hold_at, excluded_at, last_status_change_at, last_contact_at, master_lender_id, selected_contact_id, created_at, updated_at"
    ).eq("deal_id", deal_id).order("last_status_change_at", { ascending: false, nullsFirst: false });
    if (error) {
      console.error("[list_deal_funding_sources] query error", {
        deal_id,
        user_id: ctx.getUserId?.(),
        message: error.message
      });
      return errorResult(error.message);
    }
    const rows = data ?? [];
    console.log("[list_deal_funding_sources] ok", {
      deal_id,
      user_id: ctx.getUserId?.(),
      count: rows.length
    });
    return textResult(rows, { count: rows.length, deal_id, deal_visible: true });
  }
});

// src/lib/mcp/tools/get-daily-rundown.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z20 } from "npm:zod@^3.23.0";

// src/lib/mcp/rundownAccess.ts
var RUNDOWN_ALLOWED_EMAIL = "jturner@5thline.co";
function requireRundownAccess(ctx) {
  if (!ctx.isAuthenticated()) {
    return errorResult("Not authenticated");
  }
  const email = (ctx.getUserEmail?.() ?? "").toLowerCase();
  if (email !== RUNDOWN_ALLOWED_EMAIL) {
    return errorResult(
      `Daily rundown access is restricted. Signed-in user must be ${RUNDOWN_ALLOWED_EMAIL}.`
    );
  }
  return null;
}
async function logRundownAudit(ctx, action, payload = {}, itemId = null, initiatedBy = "openclaw") {
  try {
    const sb = supabaseForUser(ctx);
    await sb.from("daily_rundown_audit_log").insert({
      user_id: ctx.getUserId(),
      user_email: ctx.getUserEmail?.() ?? null,
      action,
      initiated_by: initiatedBy,
      item_id: itemId,
      payload
    });
  } catch (err) {
    console.error("[rundown-audit] failed to write audit row", err);
  }
}

// src/lib/mcp/tools/get-daily-rundown.ts
var get_daily_rundown_default = defineTool20({
  name: "get_daily_rundown",
  title: "Get daily rundown",
  description: "Read the signed-in user's daily rundown items in display order. Restricted to jturner@5thline.co.",
  inputSchema: {
    status: z20.enum(["pending", "complete", "all"]).default("all"),
    limit: z20.number().int().min(1).max(200).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    const gate = requireRundownAccess(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    let q = sb.from("daily_rundown_items").select("id, title, content, status, sort_order, source, completed_at, created_at, updated_at").order("sort_order", { ascending: true }).order("created_at", { ascending: true }).limit(limit);
    if (status !== "all") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    await logRundownAudit(ctx, "get_daily_rundown", { status, count: data?.length ?? 0 });
    return textResult(data ?? [], { count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/add-daily-rundown-item.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z21 } from "npm:zod@^3.23.0";
var add_daily_rundown_item_default = defineTool21({
  name: "add_daily_rundown_item",
  title: "Add daily rundown item",
  description: "Append a new item to the signed-in user's daily rundown. Restricted to jturner@5thline.co. sort_order defaults to the end of the list.",
  inputSchema: {
    title: z21.string().trim().min(1).max(500),
    content: z21.string().max(1e4).optional(),
    sort_order: z21.number().int().optional(),
    source: z21.string().max(50).optional().describe("Origin marker, e.g. 'openclaw' or 'user'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, content, sort_order, source }, ctx) => {
    const gate = requireRundownAccess(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    let nextOrder = sort_order;
    if (nextOrder === void 0) {
      const { data: tail } = await sb.from("daily_rundown_items").select("sort_order").order("sort_order", { ascending: false }).limit(1);
      nextOrder = (tail?.[0]?.sort_order ?? 0) + 10;
    }
    const { data, error } = await sb.from("daily_rundown_items").insert({
      user_id: userId,
      user_email: RUNDOWN_ALLOWED_EMAIL,
      title,
      content: content ?? null,
      sort_order: nextOrder,
      source: source ?? "openclaw",
      created_by: userId,
      updated_by: userId
    }).select().maybeSingle();
    if (error) return errorResult(error.message);
    await logRundownAudit(ctx, "add_daily_rundown_item", { title, sort_order: nextOrder }, data?.id ?? null);
    return textResult(data, { item_id: data?.id });
  }
});

// src/lib/mcp/tools/update-daily-rundown-item.ts
import { defineTool as defineTool22 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z22 } from "npm:zod@^3.23.0";
var update_daily_rundown_item_default = defineTool22({
  name: "update_daily_rundown_item",
  title: "Update daily rundown item",
  description: "Edit an existing rundown item's title, content, sort_order, or source. Restricted to jturner@5thline.co and their own rows.",
  inputSchema: {
    id: z22.string().uuid(),
    title: z22.string().trim().min(1).max(500).optional(),
    content: z22.string().max(1e4).nullable().optional(),
    sort_order: z22.number().int().optional(),
    source: z22.string().max(50).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ id, ...patch }, ctx) => {
    const gate = requireRundownAccess(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    const update = { updated_by: ctx.getUserId() };
    for (const [k, v] of Object.entries(patch)) if (v !== void 0) update[k] = v;
    const { data, error } = await sb.from("daily_rundown_items").update(update).eq("id", id).select().maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Rundown item not found or not accessible.");
    await logRundownAudit(ctx, "update_daily_rundown_item", { id, patch }, id);
    return textResult(data, { item_id: id });
  }
});

// src/lib/mcp/tools/complete-daily-rundown-item.ts
import { defineTool as defineTool23 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z23 } from "npm:zod@^3.23.0";
var complete_daily_rundown_item_default = defineTool23({
  name: "complete_daily_rundown_item",
  title: "Complete or reopen daily rundown item",
  description: "Mark a rundown item as complete or pending. Restricted to jturner@5thline.co and their own rows.",
  inputSchema: {
    id: z23.string().uuid(),
    complete: z23.boolean().default(true)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, complete }, ctx) => {
    const gate = requireRundownAccess(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("daily_rundown_items").update({ status: complete ? "complete" : "pending", updated_by: ctx.getUserId() }).eq("id", id).select().maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Rundown item not found or not accessible.");
    await logRundownAudit(
      ctx,
      complete ? "complete_daily_rundown_item" : "reopen_daily_rundown_item",
      { id },
      id
    );
    return textResult(data, { item_id: id, status: data.status });
  }
});

// src/lib/mcp/tools/reorder-daily-rundown-items.ts
import { defineTool as defineTool24 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z24 } from "npm:zod@^3.23.0";
var reorder_daily_rundown_items_default = defineTool24({
  name: "reorder_daily_rundown_items",
  title: "Reorder daily rundown items",
  description: "Apply a new display order to rundown items. Accepts an array of {id, sort_order} \u2014 only rows owned by the signed-in user (jturner@5thline.co) are updated.",
  inputSchema: {
    items: z24.array(z24.object({ id: z24.string().uuid(), sort_order: z24.number().int() })).min(1).max(200)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ items }, ctx) => {
    const gate = requireRundownAccess(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const results = [];
    for (const it of items) {
      const { error } = await sb.from("daily_rundown_items").update({ sort_order: it.sort_order, updated_by: userId }).eq("id", it.id);
      results.push({ id: it.id, ok: !error, ...error ? { error: error.message } : {} });
    }
    const failed = results.filter((r) => !r.ok);
    if (failed.length === items.length) return errorResult(`All updates failed: ${failed[0].error ?? "unknown"}`);
    await logRundownAudit(ctx, "reorder_daily_rundown_items", { count: items.length, failed: failed.length });
    return textResult({ updated: items.length - failed.length, failed }, { count: items.length });
  }
});

// src/lib/mcp/index.ts
var projectRef = "tgkksvazruzbghssnxde";
var mcp_default = defineMcp({
  name: "naitive-api",
  title: "naitive API",
  version: "0.1.0",
  instructions: "Tools for the naitive deal-management platform. Callers act as the signed-in naitive user; all reads and writes respect the user's company scoping and access. Use `list_deals`/`get_deal` to inspect deals, `update_deal` to move stage or edit fields, `list_tasks`/`create_task`/`complete_task` for task work, `search_contacts`/`search_companies`/`create_contact`/`create_company` for CRM lookups, `search_lenders`/`add_lender_to_deal` for the funding-source directory, `list_deal_funding_sources` to read the lenders attached to a specific deal (matches the deal's Funding Sources tab), and \u2014 for deep deal context \u2014 `search_deal_notes`, `list_deal_activity`, `search_deal_documents`, `get_deal_document`, `search_deal_emails`, and `search_deal_recordings` to retrieve notes, timeline events, files, email history, and meeting transcripts scoped to a specific deal. Daily rundown tools (`get_daily_rundown`, `add_daily_rundown_item`, `update_daily_rundown_item`, `complete_daily_rundown_item`, `reorder_daily_rundown_items`) manage the personal dashboard rundown \u2014 access is restricted to jturner@5thline.co and enforced at the database (RLS) and edge-function layers.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_deals_default,
    get_deal_default,
    update_deal_default,
    list_tasks_default,
    create_task_default,
    complete_task_default,
    search_contacts_default,
    search_companies_default,
    create_contact_default,
    create_company_default,
    search_lenders_default,
    add_lender_to_deal_default,
    search_deal_notes_default,
    list_deal_activity_default,
    search_deal_documents_default,
    get_deal_document_default,
    search_deal_emails_default,
    search_deal_recordings_default,
    list_deal_funding_sources_default,
    get_daily_rundown_default,
    add_daily_rundown_item_default,
    update_daily_rundown_item_default,
    complete_daily_rundown_item_default,
    reorder_daily_rundown_items_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
