// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-deals.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.23.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  const token = ctx.getToken();
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
  }
  return null;
}
function textResult(payload, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    ...structured ? { structuredContent: structured } : {}
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-deals.ts
var list_deals_default = defineTool({
  name: "list_deals",
  title: "List deals",
  description: "List the naitive deals the signed-in user can see. Optionally filter by stage, pipeline_id, or a text query against the company/deal name. Returns id, company, stage, value, closing_date, pipeline_id, deal_owner, updated_at.",
  inputSchema: {
    query: z.string().trim().min(1).max(200).optional().describe("Substring search across the company / deal name."),
    stage: z.string().trim().min(1).max(100).optional().describe("Exact stage id (e.g. 'nda-needs-list', 'on-deck')."),
    pipeline_id: z.string().uuid().optional(),
    limit: z.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, stage, pipeline_id, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    let q = sb.from("deals").select("id, company, stage, value, closing_date, pipeline_id, deal_owner, manager, updated_at").order("updated_at", { ascending: false }).limit(limit);
    if (stage) q = q.eq("stage", stage);
    if (pipeline_id) q = q.eq("pipeline_id", pipeline_id);
    if (query) q = q.ilike("company", `%${query}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(data ?? [], { count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/get-deal.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.23.0";
var get_deal_default = defineTool2({
  name: "get_deal",
  title: "Get deal",
  description: "Fetch a single deal by id with its full record, plus recent status notes, tasks, and attached lenders.",
  inputSchema: {
    deal_id: z2.string().uuid(),
    include_tasks: z2.boolean().default(true),
    include_lenders: z2.boolean().default(true)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id, include_tasks, include_lenders }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const { data: deal, error } = await sb.from("deals").select("*").eq("id", deal_id).maybeSingle();
    if (error) return errorResult(error.message);
    if (!deal) return errorResult("Deal not found or you do not have access.");
    const [tasksRes, lendersRes] = await Promise.all([
      include_tasks ? sb.from("tasks").select("id, title, status, due_date, priority, assignee, created_at").eq("deal_id", deal_id).order("created_at", { ascending: false }).limit(50) : Promise.resolve({ data: null, error: null }),
      include_lenders ? sb.from("deal_lenders").select("id, lender_id, status, stage, updated_at").eq("deal_id", deal_id).order("updated_at", { ascending: false }).limit(200) : Promise.resolve({ data: null, error: null })
    ]);
    return textResult({
      deal,
      tasks: tasksRes.data ?? [],
      lenders: lendersRes.data ?? []
    });
  }
});

// src/lib/mcp/tools/update-deal.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.23.0";
var update_deal_default = defineTool3({
  name: "update_deal",
  title: "Update deal",
  description: "Update a deal's stage and/or high-level fields (value, closing_date, deal_owner, manager, narrative, is_flagged, flag_notes). Only fields you pass are changed. Returns the updated deal row.",
  inputSchema: {
    deal_id: z3.string().uuid(),
    stage: z3.string().trim().min(1).max(100).optional(),
    value: z3.number().nonnegative().optional(),
    closing_date: z3.string().nullable().optional().describe("ISO date, or null to clear."),
    deal_owner: z3.string().trim().max(200).optional(),
    manager: z3.string().trim().max(200).optional(),
    narrative: z3.string().max(2e4).optional(),
    is_flagged: z3.boolean().optional(),
    flag_notes: z3.string().max(2e3).nullable().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const { deal_id, ...rest } = input;
    const patch = {};
    for (const [k, v] of Object.entries(rest)) if (v !== void 0) patch[k] = v;
    if (Object.keys(patch).length === 0) return errorResult("No fields to update.");
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("deals").update(patch).eq("id", deal_id).select().maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Deal not found or you do not have permission to update it.");
    return textResult(data, { deal_id });
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.23.0";
var list_tasks_default = defineTool4({
  name: "list_tasks",
  title: "List tasks",
  description: "List tasks the signed-in user can see, optionally filtered by deal, status, or assignee.",
  inputSchema: {
    deal_id: z4.string().uuid().optional(),
    status: z4.enum(["not_started", "in_progress", "completed", "blocked", "cancelled"]).optional(),
    assignee: z4.string().trim().max(200).optional(),
    query: z4.string().trim().max(200).optional(),
    limit: z4.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id, status, assignee, query, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    let q = sb.from("tasks").select("id, title, description, status, priority, due_date, assignee, deal_id, contact_id, company_id, created_at").order("due_date", { ascending: true, nullsFirst: false }).limit(limit);
    if (deal_id) q = q.eq("deal_id", deal_id);
    if (status) q = q.eq("status", status);
    if (assignee) q = q.ilike("assignee", `%${assignee}%`);
    if (query) q = q.ilike("title", `%${query}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(data ?? [], { count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.23.0";
var create_task_default = defineTool5({
  name: "create_task",
  title: "Create task",
  description: "Create a task, optionally tied to a deal, contact, or company. Returns the created row.",
  inputSchema: {
    title: z5.string().trim().min(1).max(500),
    description: z5.string().max(1e4).optional(),
    due_date: z5.string().nullable().optional().describe("ISO date."),
    priority: z5.enum(["low", "medium", "high", "urgent"]).optional(),
    assignee: z5.string().trim().max(200).optional(),
    deal_id: z5.string().uuid().optional(),
    contact_id: z5.string().uuid().optional(),
    company_id: z5.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const row = {
      title: input.title,
      status: "not_started",
      created_by: ctx.getUserId()
    };
    for (const k of ["description", "due_date", "priority", "assignee", "deal_id", "contact_id", "company_id"]) {
      if (input[k] !== void 0) row[k] = input[k];
    }
    const { data, error } = await sb.from("tasks").insert(row).select().maybeSingle();
    if (error) return errorResult(error.message);
    return textResult(data, { task_id: data?.id });
  }
});

// src/lib/mcp/tools/complete-task.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^3.23.0";
var complete_task_default = defineTool6({
  name: "complete_task",
  title: "Complete task",
  description: "Mark a task as completed.",
  inputSchema: { task_id: z6.string().uuid() },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ task_id }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("tasks").update({ status: "completed", completed_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", task_id).select().maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Task not found or not accessible.");
    return textResult(data);
  }
});

// src/lib/mcp/tools/search-contacts.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z7 } from "npm:zod@^3.23.0";
var search_contacts_default = defineTool7({
  name: "search_contacts",
  title: "Search contacts",
  description: "Search CRM contacts by name, email, or domain. Returns id, name, email, phone, domain, title, company.",
  inputSchema: {
    query: z7.string().trim().min(1).max(200),
    limit: z7.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const like = `%${query}%`;
    const { data, error } = await sb.from("contacts").select("id, first_name, last_name, email, phone, website_url, job_title, company, created_at").or(`first_name.ilike.${like},last_name.ilike.${like},email.ilike.${like},website_url.ilike.${like},company.ilike.${like}`).limit(limit);
    if (error) return errorResult(error.message);
    return textResult(data ?? [], { count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/search-companies.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z8 } from "npm:zod@^3.23.0";
var search_companies_default = defineTool8({
  name: "search_companies",
  title: "Search companies",
  description: "Search CRM companies by name or domain.",
  inputSchema: {
    query: z8.string().trim().min(1).max(200),
    limit: z8.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const like = `%${query}%`;
    const { data, error } = await sb.from("crm_companies").select("id, name, website_url, industry, city, state, created_at").or(`name.ilike.${like},website_url.ilike.${like}`).limit(limit);
    if (error) return errorResult(error.message);
    return textResult(data ?? [], { count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/create-contact.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z9 } from "npm:zod@^3.23.0";
var create_contact_default = defineTool9({
  name: "create_contact",
  title: "Create contact",
  description: "Create a CRM contact. Provide at minimum an email or first_name/last_name.",
  inputSchema: {
    first_name: z9.string().trim().max(200).optional(),
    last_name: z9.string().trim().max(200).optional(),
    email: z9.string().trim().email().optional(),
    phone: z9.string().trim().max(50).optional(),
    website_url: z9.string().trim().max(500).optional().describe("Contact domain (matches to company)."),
    job_title: z9.string().trim().max(200).optional(),
    company: z9.string().trim().max(200).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    if (!input.email && !input.first_name && !input.last_name) {
      return errorResult("Provide at least email or first_name/last_name.");
    }
    const sb = supabaseForUser(ctx);
    const row = { created_by: ctx.getUserId() };
    for (const [k, v] of Object.entries(input)) if (v !== void 0) row[k] = v;
    const { data, error } = await sb.from("contacts").insert(row).select("id, first_name, last_name, email, website_url").maybeSingle();
    if (error) return errorResult(error.message);
    return textResult(data, { contact_id: data?.id });
  }
});

// src/lib/mcp/tools/create-company.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z10 } from "npm:zod@^3.23.0";
var create_company_default = defineTool10({
  name: "create_company",
  title: "Create company",
  description: "Create a CRM company record.",
  inputSchema: {
    name: z10.string().trim().min(1).max(300),
    website_url: z10.string().trim().max(500).optional(),
    industry: z10.string().trim().max(200).optional(),
    city: z10.string().trim().max(200).optional(),
    state: z10.string().trim().max(200).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const row = { created_by: ctx.getUserId() };
    for (const [k, v] of Object.entries(input)) if (v !== void 0) row[k] = v;
    const { data, error } = await sb.from("crm_companies").insert(row).select("id, name, website_url").maybeSingle();
    if (error) return errorResult(error.message);
    return textResult(data, { company_id: data?.id });
  }
});

// src/lib/mcp/tools/search-lenders.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z11 } from "npm:zod@^3.23.0";
var search_lenders_default = defineTool11({
  name: "search_lenders",
  title: "Search funding sources / lenders",
  description: "Search the master lender directory by name, product, or geography. Optionally filter by deal_size (returns lenders whose min_deal_size <= size <= max_deal_size).",
  inputSchema: {
    query: z11.string().trim().max(200).optional(),
    deal_size: z11.number().nonnegative().optional(),
    limit: z11.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, deal_size, limit }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    let q = sb.from("master_lenders").select("id, name, lender_type, tier, min_deal_size, max_deal_size, loan_types, geographies, website").limit(limit);
    if (query) q = q.ilike("name", `%${query}%`);
    if (deal_size !== void 0) q = q.lte("min_deal_size", deal_size).gte("max_deal_size", deal_size);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(data ?? [], { count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/add-lender-to-deal.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z12 } from "npm:zod@^3.23.0";
var add_lender_to_deal_default = defineTool12({
  name: "add_lender_to_deal",
  title: "Add lender to deal",
  description: "Attach a funding source / lender to a deal. Per project rule, new lenders default to the 'On Deck' stage.",
  inputSchema: {
    deal_id: z12.string().uuid(),
    lender_id: z12.string().uuid(),
    stage: z12.string().trim().max(100).default("on-deck"),
    status: z12.string().trim().max(100).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ deal_id, lender_id, stage, status }, ctx) => {
    const authErr = requireAuth(ctx);
    if (authErr) return authErr;
    const sb = supabaseForUser(ctx);
    const row = { deal_id, lender_id, stage, created_by: ctx.getUserId() };
    if (status) row.status = status;
    const { data, error } = await sb.from("deal_lenders").insert(row).select().maybeSingle();
    if (error) return errorResult(error.message);
    return textResult(data, { deal_lender_id: data?.id });
  }
});

// src/lib/mcp/index.ts
var projectRef = "tgkksvazruzbghssnxde";
var mcp_default = defineMcp({
  name: "naitive-api",
  title: "naitive API",
  version: "0.1.0",
  instructions: "Tools for the naitive deal-management platform. Callers act as the signed-in naitive user; all reads and writes respect the user's company scoping and access. Use `list_deals`/`get_deal` to inspect deals, `update_deal` to move stage or edit fields, `list_tasks`/`create_task`/`complete_task` for task work, `search_contacts`/`search_companies`/`create_contact`/`create_company` for CRM lookups, and `search_lenders`/`add_lender_to_deal` to work with the funding-source directory.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_deals_default,
    get_deal_default,
    update_deal_default,
    list_tasks_default,
    create_task_default,
    complete_task_default,
    search_contacts_default,
    search_companies_default,
    create_contact_default,
    create_company_default,
    search_lenders_default,
    add_lender_to_deal_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
