UPDATE deals SET status = 'archived', updated_at = now() WHERE company IN (
'Restore First Health',
'MDC/Centre Lane Partners',
'JB Cap/ePublishing',
'Syntropy Growth Partners - All Filters',
'Fly Hugz',
'Duracell Power Center',
'Mode Mobile',
'LiveLike',
'MVE',
'Blue Line Equipment',
'TableTop Tycoon',
'Gauge (Automotive)',
'Safety NetAccess',
'InnoCom',
'GET Group North America',
'Breaktime Media',
'Canela Media',
'Hello Hero',
'Freight Farms',
'Phase Change',
'Care Solace',
'SoapBox Soaps',
'Voxy',
'Merlin Labs',
'Extole',
'Thrio',
'BrightOrder',
'Modern Sprout',
'Citcon',
'Ellis Brooklyn',
'Brondell',
'Issuu',
'Episode Six',
'Lower.com',
'Esme Learning',
'PAIRIN',
'CrateJoy',
'Coinme',
'Kunai',
'Bio365',
'3BG Supply',
'EarthGrid',
'roomrs',
'Rango Wireless',
'Virtuix',
'flexEngage',
'Satisfi Labs',
'Catalia Health',
'Orb Health',
'Pathstream',
'Reveal Group',
'VitusVet',
'American Nitrile',
'Losant',
'GreenTank - CapEx',
'ExecVision',
'LegalMation',
'K2P',
'GreenTank',
'Clarify Health',
'Allovue',
'Arryved',
'Ciphertrace',
'Kallpod',
'Anonos',
'Banzai',
'PharmaSmart',
'Open Education',
'Fraxion',
'Critical Mention',
'IMPT',
'Ollie',
'Room',
'Jetpatch',
'Circle',
'Sapience Analytics',
'Fetch Package',
'Legends of Learning',
'Valisure',
'Abpro',
'Truefill',
'Corsa Technology CAPEX',
'InfoBionic Inc.',
'OpenWeb',
'Extole - ABL',
'J Ferg',
'ThinkCERCA',
'Landr',
'Funraise',
'Newtopia',
'GiveGab',
'Buzz Points',
'80 Acres Farms',
'Sepragen',
'Bear Robotics',
'Picnic',
'Hint Health Inc.',
'ENGAGE Mobilize',
'GovInvest',
'Sixgill',
'PacketFabric - CapEx',
'Starcity',
'Art & Craft Entertainment',
'CRC - Contract Financing',
'Aura Frames',
'BandwidthX',
'PsiQ',
'Trice Medical',
'Candor Insurance',
'Air2O',
'CRC - CapEx',
'Lulutrip',
'HaptX',
'Full Measure Education',
'DemandJump',
'Bedrock Analytics',
'Blok Party',
'C3Nano',
'Astro Digital',
'Brandable',
'DECA Games',
'Axiom Energy',
'American Gene Technologies',
'Faraday Future - CapEx/GC',
'CRC - ABL',
'ALDGreen',
'Swiftmile - CapEx',
'EcoCups - CapEx / AR',
'RGS Energy',
'Approyo - WC',
'7 Mindsets',
'Miles',
'Wonder Workshop',
'Antheia Inc',
'Portfolio BI',
'Earth Daily',
'Savari',
'Acquire Corp.',
'Interior Define Inc.',
'Global Graphene Group Inc',
'EXPLORAMED NC7, INC (Willow Pump)',
'Litmus Automation',
'TruTag Technologies, Inc.',
'Microbion',
'Coherix',
'FDNA',
'Urotronic',
'EDP Biotech',
'IDSS Holdings, Inc.',
'Novus Partners Inc',
'Notarize',
'Rocean',
'LISNR',
'Bear Robotics - CapEx'
)