DO $$
DECLARE
  bc_id uuid;
  d_id uuid;
  rec record;
  notes_data jsonb := '[
    {"name":"Club Five Health","note":"Team held meeting on 2026.01.20 with management. JL sent NDA and diligence request same day. JL connected with John Hanna on 2026.01.21 re feedback. Hanna suggested a bit too \"heavy handed\" on the deal being a \"heavy lift\" but management still keen to sign NDA and be responsive to diligence request list. Team on standby and to leverage Steve Landzberg construction equipment lending connections once materials on hand and teaser built out. JL to follow up 2026.01.27 if no word from management by then. JL to give founder, Ravi, a call on 2026.01.26. Ravi 2629893880. JL spoke to Ravi on 2026.01.26 - he indicated he was convinced and now will sign NDA and share documents, just concerned that we wont be able to raise the capital 5-10M - will be a facility that flexes with the size of the company, we as a responsible advisor dont want to put 20M on the business now anyway, would cripple it, facility size needs to scale with profitability."},
    {"name":"TriNeo","note":"JL and GB holding kickoff call with Kirk at 3pm ET on 1/27. Per Kirk, \"in capital raising phase\" of renewable energy fund HOME / Trineo Energy Inc. 4 projects. getting project financing lined up for all. lenders currently circling. Kirk open to GB / JL opining to see what we can do on terms. looking for 60m of equity, 60m of debt. renewables project finance, KK acres of land, already well into permitting phases, interest from Microsoft and others re facilitation of data center buildouts on site, etc. Process sounds like its moving quickly. JL sent email on 2026.01.27 re request for NDA from Kirk - VDR already ready, JL to review and get back final week of January. Polly sent out email on 2026.02.09 with NDA to Kirk. JL to follow up with Kirk on executed copy and VDR 2nd week of february if nothing by then."},
    {"name":"BoxPort","note":"JL connected with Adam on 2026.01.16. Import/export arbitrage model. Credible international banks hold security interest vs. end producers of goods, lending comfort re downside coverage. Adam requires more flexible capital partner than existing Greenwich-based PE firm that has provided $240M line to him, deployable in $20M monthly increments, as existing arrangement does not allow him to act quickly enough. Nature of the space is that deal windows are tight (nature of arbitrage). Key is a partner who is nimble and can deploy bridge lending solutions at a moment''s notice but also has deep pockets. Team to connect with Adam on 2026.01.22 to further discuss."},
    {"name":"TicketVision","note":"Interesting ticketing arbitrage model. Partners with Stubhub and others. Offers the equivalent of a trading \"limit order\" in a DTC app allowing people to lock in preferred concert prices. Company has operated at ~$300K/mo in revenue at 41% profit margin for 2 years, per Dillon, founder. Team of 4-5 individuals. Implies roughly $3.5M of revenue, $1.5M of profit. Looking for capital, wants to explore what situations are available. Debrief scheduled for 3rd week of January. JL sent diligence request list on 2026.01.15."},
    {"name":"GenFuel","note":"Company performs organic recycling / \"refueling?\" services, per John Hanna. JL discussed briefly with John Hanna on 2026.01.21. Hanna suggested waiting on board deck and financials from Company and will be back to JL in short-term. Nature of the opportunity is a bit opaque but sounds like a hybrid equipment financing / cash flow lending situation."},
    {"name":"Jean-Pierre","note":"12 unit all-leased womens-wear dress retailer located in affluent, upper-tier FL beach towns. Owned and run by aging designer JPK. JPK looking to retire. Ask is $4.5M. Allegedly willing to hold $500K in seller note. JL worked with John Hanna in 2024-2025 in an attempt to acquire through Old Georgian Ventures. JPK was firm on value and went with another amateur SBA buyer, an arrangement which since fell through. John submitted revised offer of $4M, $500K Seller, on 2026.02.17 post JL review of 2025 year end financials. 2026.02.23 - JL sent note to Hanna requesting NDA from company. 2026.03.13 - JL to prepare and share underwriting memo with groups. 2026.03.16 JL prepared underwriting memo and shared with John Hanna. Spoke with John and Oscar on May 27th, 2026. Oscar has to take care of his personal issues. Once those are out of the way, we can move forward."},
    {"name":"EVRNU","note":"Recycled cotton and other materials. Huge Euro-based regulatory headwinds. 3 patents. collaborations with burberry, zara. need $50M of financing. $30M accounted for by USDA. $10M additional project equity needed, along with $10M more in operational funding. As of 2026.01.27, next steps are getting VDR access. JL already sent NDA, client got back same day. Team then to get back latest 48 hours later with any questions and begin no-names reachout asap. Fantastic call with Bertrand Deleuse on 2026.02.12. Good call with Stacy and Aidan on 2026.02.16. 2026.03.13 - team sent memo to Stacy and Aidan. 2026.03.17 team sent next cut of memo to Stacy and Aidan. Awaiting final comments."},
    {"name":"PiperWai","note":"Sarah Ribner, successful Shark Tank Alumn, has built impressive womens skincare retail brand with \"real\" revenue and EBITDA. looking to consolidate the beauty space later this year. Sarah also passed along additional opportunity on 2026.02.02 re $1.3M funding gap in friend''s Series A."},
    {"name":"Splendies","note":"I7 investments looking to facilitate e-commerce rollup strategy. JL connected with Yann on 2026.02.02. JL sent engagement agreement to Yann Com on 2026.02.12. JL sent Consulting Agreement and underwriting memo to Yann on 2026.03.01. JL introd Yann to Argosy and Commercial Finance Partners on 2026.03.04. 2026.03.17 JL postponed call with Kevin / Founderpath. 2026.03.27 JL sent note to Justin Rivera re 2-4x leverage cash flow lenders."},
    {"name":"Level 7","note":"I7 investments looking to facilitate e-commerce rollup strategy. JL connected with Yann on 2026.02.02. JL sent engagement agreement to Yann Com on 2026.02.12. JL sent Consulting Agreement and underwriting memo to Yann on 2026.03.01. JL introd Yann to Argosy and Commercial Finance Partners on 2026.03.04. 2026.03.17 JL postponed call with Kevin / Founderpath. 2026.03.27 JL sent note to Justin Rivera re 2-4x leverage cash flow lenders."},
    {"name":"Candela","note":"Liquor brand. Production outsourced in South America. Company was sold to Diageo for LSD-MSD $mm. CEO since has doubled down and given the brand a complete facelift. Need $5M to fund purchase orders. JL sent diligence request on 2026.01.02. JL followed up with Russo on 2026.01.19. Waiting on full package as of 2026.01.21."},
    {"name":"ThinkClean","note":"Airport luggage sanitization solution. Currently pre-revenue but contracts in place at JFK and couple other major hubs. Company requires $1M to cover capital buildout. Low potential as an equipment financing play. Blount thinking through who can be introd to team, as of 2026.01.21. Rodney reached out to JL on 2026.01.29 requesting update."},
    {"name":"Native Traits","note":"Corn yield enhancer. Seller of IP. CEO claims significant potential for 1:13. But seems very early stage, not well thought out. Blount to spend little to no time here."},
    {"name":"Global Auto","note":"Tri-oceanic classic autos hedge fund opportunity. Uniting of Will Keiser of NY, David Spickett of the UK. Major push here after big news mid-January 2026 of record setting classic autos prices. Blount submitted attached proposal in late 2025. As of 2026.01.21, JL waiting on materials from David Spickett."},
    {"name":"NXTMoves","note":"Backend platform for banks looking to manage transaction data. Real traction, tracking to ~$8M in revenue in 2026. Team held call with management on 2026.01.28. Team caught up with Steve N on 2026.02.16, message being no bid for debt yet. JL texted Steve N on 2026.02.24 - Blount happy to re-engage post-launch of programs in March."},
    {"name":"Compound Foundry","note":"Incredibly important relation. Terry Turpin multi-exit 9-figure entrepreneur. $60M revenue. 10% EBIT margins. 2026 budget calls for $100M revenue. Company needs to get the house in order on the equipment financing side. JL followed up with Terry on 2026.01.21. JL followed up on 2026.03.10 on LinkedIn. 2026.04.07 - JL sent text to Terry and left VM."},
    {"name":"Honor Pet","note":"Multi-exit founder. Pet aftercare services. Looking for $1M in equity today. JL and team to review ahead of debrief. Team held call with Eli on 2026.01.23. JL connected with Greg Doutre / Priority Capital on 2026.02.03 - suggested may be of interest."},
    {"name":"Eflion","note":"Highly accomplished CFO, working for a battery company looking to raise $30M. Has had some bad experiences with prior advisors. JL followed up with Yaser on 2026.01.21 after sharing NDA a couple weeks prior."},
    {"name":"Med Device","note":"Strong relationship of JL with healthcare sell-side banker in FL. 500K EBITDA med device manufacturer with real revenue that needs $5-10M to finance a facility/equipment buildout. Peter indicated management would be traveling until last week of January 2026. JL to reach out then."},
    {"name":"Urban Electric","note":"Zinc-ion battery manufacturer. High cost but also high safety rating. Held conversation with Gabe in early january 2026. JL sent diligence request list. No response as of 2026.01.21. JL to follow up with Gabe last week of January."},
    {"name":"HealthFleet","note":"Anti-obesity, content-library platform. 80M in NOLs, company burning $100K a month. ARR financing a possibility but would likely not even get him $1M in debt. JL set up call with David Tradburks, but David on 2026.01.20 indicated it''s a pass. JL to call David on 2026.01.22."},
    {"name":"FFO Cannabis","note":"GB ran down 2nd week of January 2026. Too much grey area. Blount opted to be upfront with Tom rather than trying and coming back with nothing."},
    {"name":"BlueNalu","note":"Cell-based high end tuna manufacturer. Require equipment financing in immediate term to the tune of $500K. JL shared NDA and diligence request list with CFO in early-mid-January 2026. JL connected with Greg Doutre / Priority Capital on 2026.02.03. JL followed up with Ed on 2026.02.04. JL called Ed on 2026.04.08 and left VM. JL sent follow up on 2026.05.14."},
    {"name":"OpenDroids","note":"Very impressive, hype house founder. Hardware robotics company. Company remains pre-revenue but have $11.8M contract. CEO considering an IPO. JL sent note to CFO contact, Varun, on 2026.01.19. JL followed up yet again on 2026.02.03. JL sent following email on 2026.02.12 - \"happy to move on here.\" Sent SLandzberg materials on this on 2026.03.05."},
    {"name":"Tech-Enabled","note":"CFO exploring a senior refinancing on behalf of an established tech-enabled services operator. Existing note has a current balance of $5M. The Company generated $2.8M in EBITDA on $34.9M of Revenue in CY24. JL prepared draft email to be sent out to prospective lenders by GB."},
    {"name":"Buyside Fund","note":"John Hanna indicated friend of his based in U.K. looking to raise credit fund to the tune of $50-100M to deploy into lower-mid-market companies and RE in Europe and UK."},
    {"name":"Phoenix Footwear","note":"Footwear brand getting crushed by international tariffs. $15-20M in revenue, breakeven EBITDA. Looking to acquire competitor. GB and JL connected with Jim on 2026.01.29 - Jim needs new AR/Inventory facility, $6M. Package received on 2026.01.29. JL to review on 2026.01.31."},
    {"name":"Voda Restoration","note":"Very impressive founder, long-standing relation of JL. built out franchisor providing facility maintenance services with 100+ franchisees, currently doing ~$20-30M revenue and ~$5M EBITDA. need $1-2M in funding now for scaling. JL sent NDA in Nov/December 2025."},
    {"name":"FarrPro","note":"Chicken Euthanasia N2 equipment financing. Need $2M to buy 4 machines. JL sent engagement letter 2nd week of January 2026. GB sent amended consulting engagement agreement on 2026.01.28. 2026.02.23 Call Action Items. 2026.03.09 JL shared latest model and first cut of memo with Amos and Luke. 2026.04.23 Process Email Sent to Luke and Amos. Good catchup on 2026.05.28 with Luke - raising equity in michigan. JL waiting on financials from AES and actual transaction docs ahead of merger."},
    {"name":"Watches","note":"Opportunity to acquire the domain and the business. Ask currently is $4.5M. GB going out to market with teaser JL prepared. Lender reachout beginning as of 2026.01.29. John Hanna called JL on 2026.02.08 indicating he submitted $3M offer. 2026.02.17 - financials revised down to $550K"}
  ]'::jsonb;
BEGIN
  SELECT id INTO bc_id FROM public.companies WHERE name = 'Blount Capital' LIMIT 1;
  IF bc_id IS NULL THEN
    RAISE NOTICE 'Blount Capital company not found';
    RETURN;
  END IF;

  FOR rec IN SELECT * FROM jsonb_to_recordset(notes_data) AS x(name text, note text) LOOP
    SELECT id INTO d_id FROM public.deals
      WHERE company_id = bc_id AND company ILIKE '%' || rec.name || '%'
      LIMIT 1;
    IF d_id IS NULL THEN
      CONTINUE;
    END IF;
    IF EXISTS (
      SELECT 1 FROM public.deal_status_notes
      WHERE deal_id = d_id AND left(note, 100) = left(rec.note, 100)
    ) THEN
      CONTINUE;
    END IF;
    INSERT INTO public.deal_status_notes (deal_id, user_id, note, created_at)
    VALUES (d_id, NULL, rec.note, now());
  END LOOP;
END $$;