DO $$
DECLARE
  bc_id uuid;
BEGIN
  SELECT id INTO bc_id FROM public.companies WHERE name = 'Blount Capital' LIMIT 1;
  IF bc_id IS NULL THEN
    RAISE NOTICE 'Blount Capital company not found; skipping narrative backfill.';
    RETURN;
  END IF;

  UPDATE public.deals SET narrative = $n$Ryan Morgan and JL spoke on 2026.01.26. Ryan building out buy-side acquisition advisory platform, helping entrepreneurs buy companies in the 1-10M EV range. 17 companies currently expected to transact by March of this year. Needs to line up financing for some but also plugged into multiple other deals outside of these 17 i.e. an OG company that needs 12M of debt financing. Ryan also looking for funding for Acquisition Network itself, his company - currently doing 100kmo with high expenses, sounds like the company is just south of breakeven. JL and Ryan discussed getting some deals together done on the side on referral to improve his cash flow profile, at which point BCC can help him raise debt financing for Acquisition Network in other words, Ryan directs a few referral deals at BCC now, in order to get Acquisition Network into a position to itself become a BCC client. GB and JL connected with management on 2026.01.26. Wait and see - unclear if they will need BCC.$n$
    WHERE company_id = bc_id AND company ILIKE '%Acquisition Network%';

  UPDATE public.deals SET narrative = $n$Bryan Johnson spoke with JL on 2026.01.28, indicating he got response from Berel 80k followers, impressive. Berel asked for referral fee - JL directed Bryan to tell Berel 10 begin a potentially very lucrative relationship for him by BCC giving up a little more. JL sent email to Prashanna pt@globemetal.com on 2026.01.29. Prashanna replied on 2026.01.29 with one pager on deal. JL suggested call 1st week of february to discuss. JL connected with Jonathan, CFO, of Globe Metals on 2026.02.02. Sent diligence request same day. JL to discuss with GB re how to finance. JL connected with Greg Doutre Priority Capital on 2026.02.03 - suggested may be of interest. BCC to share materials and VDR access with Greg 2nd week of February. JL followed up with Jonathan on 2026.02.09 - to execute NDA later today, JL mentioned couple mezzanine lenders may be interested. JL followed up again on 2026.03.05. 2026.02.02 Call Notes: RBC Transaction based financing. Dont rely on revolving line of credit. Max loan of 8m. And have receivables finance of 13M. 19m drawn between the two. 20M 15M Inventory 25M AR - very current - all EDC insured, export development. All works from PO of client 5M order. Make use of the PO and let bank know about it, get 8M as a loan. Store materials Chinese suppliers, european ones, make some deals, buy material related to the PO. Bring it by air or boat. Have engineers that inspect at the facility. When its ready to go out, gets shipped out to the client and gets turned into an invoice or receivable. RBC will pay 90, 4.5M, 4M pays back the original loan, remainder of that gets paid off when the client pays us. Have a net 90 with largest client. Recently, had a large PO, 20 down payment, 5M US, chinese company, deal price constant throughout the year. Without that payment, 110M in sales, 4.3M in bottom line. Retained earnings is 12M. 2026 projections 142M canadian and bottom line just under 5M. Tariff expense.$n$
    WHERE company_id = bc_id AND company ILIKE '%Globe Metals%';

  UPDATE public.deals SET narrative = $n$JL VDR Review - Questions & Comments: Please elaborate how much of the improvement in effective yield from 2.0 to 2.5 from 2026 to 2028 comes from price kickers clearly enshrined in contracts now being signed? Can you explain a bit more about how you expect to increase share of wallet with customers over the 2026 through 2028 period? Why are you still projecting top customer as a third of revenue in 2028? the vendors you have in place AB Corp, BHB, checkout.com, etc. - able to handle the ramp through 2028 under existing contract terms or do you expect there will have to be a re-negotiation? what kind of logo and dollar churn does your model through 2028 assume? what are the rough splits re uses of capital pertaining to this raise between platform buildout and integrations, standing up regulatory, risk and program management and absorbing 2026 burn while you ramp? Have you run into any network bandwidth or other capacity related issues when it comes to processing higher and higher volumes of transactions? Issuing Customer Journey program development journey seems to imply heavy personnel usage on your part - how are you thinking about tracking down the right talent? can you explain a bit more specifically about why the large customer churned last year? Pipeline: are 2026 signed pipeline numbers as good as 100 locked? under what scenarios might these numbers not show up? 2024 PL Big number for contractors - what is the split of W2s vs. 1099s? What was the 130K in legal fees? NXTMoves Credit Facility: Elaborate on the role of NXTMoves Capital. 2026.05.18: held catchup with Steve Nigri awaiting updated deck, financials and pipeline to turn on debt raise in August, per Steve, which is when he expects they will be in low 7 figures of ARR. NXTMoves connecting with BOB.Ai in coming short days. Model: So there are a few revenue streams, this annual fee for new accounts, late fees which is largely deminimis, interchange revenue which is one of your core revenue streams. How are you getting to the 2 gross interchange fee? What is assumption underlying the 40K/annum of new acquisitions? Take us through the charge off assumption build? Credit Facility Term Sheets: How are you thinking about sequencing corporate operating debt raise versus the receivables facility? Would it be helpful for Blount to review the term sheets youve received for the receivables facility? Can you walk us through the key drivers behind the 23-29 gross yield assumption? Funding cost is modeled at SOFR + 400bps. Charge-offs are estimated at 2-4 annually. Delinquencies are capped at 5 for 30 DPD.$n$
    WHERE company_id = bc_id AND company ILIKE '%NXTMoves%';

  UPDATE public.deals SET narrative = $n$JL connected with Vitaly on 2026.01.28 - raising Series A, 9m, needs lead investor and seeking debt too. Wants intro on former and help on latter. Also has friend in EV charging who does 1-3M projects that he leans on debt financing for but also wants debt financing to grow his business, profitable - JL sending NDA and diligence request on 2026.01.28 and setting up 2 calls with Vitaly and friend. JL had meeting with Vitaly Devocion on 2026.04.16 - sent NDA same day. to request data and set up kickoff call thereafter. JL sent information request to Vitaly on 2026.04.22 - awaiting response. Setting up catchup for 2026.04.28 12pm ET to review and get engaged.$n$
    WHERE company_id = bc_id AND company ILIKE '%UrbanChain%';

  UPDATE public.deals SET narrative = $n$2 ventures: Important export of construction materials. 1.3M rev / 400K EBITDA in 2024. projecting 3.5M rev / 1M EBITDA in 2025. looking for inventory PO financing to expand business. Development of land, 5M needed. Getting SBA loans. Wants us to look at term sheets - open to kicking us business if we can do better. JL followed up on 2026.03.05 - great connecting earlier this year. how are things going? would love to touch base over another call. some of the strategic finance needs you outlined are right in our wheelhouse. confident we could be supportive and position you exceptionally well. perhaps we set up a time with our Managing Partner to get acquainted? Mohamed responded - The timing is a bit early now, i am not ready to discuss further till the summer probably. Okay great. we will reach out in May to touch base.$n$
    WHERE company_id = bc_id AND company ILIKE '%Texco%';

  UPDATE public.deals SET narrative = $n$JL 2026.01.28 Materials Production Review: Historical & Projected Revenue - price not a strategy, generally - why feel that subscription price increase will not result in demand destruction? why do you feel the culling of the promotional first month free will not reduce new customer entrants? what share of historical revenue is recurring? how much of the companys revenue trajectory historically can be explained by price vs. volume? how has active subscriber count evolved overtime? Margins/Expenses: what is the Companys ROAS? why was profitability so choppy historically? please break down your Y1 margin 650-1,250bps margin improvement for us? how were costs reduced by 6 per order? Value Proposition: please describe the companys value proposition and how differentiated? Transaction: how did you source this opportunity? 3.8M purchase price but trailing 3 year average profitability closer to 500K? so this is really a 7-8x multiple. JL Held Call With Michael Shen on 2026.02.27: One of the interested capital providers expects to come in close to the terms outlined, with rate perhaps higher by a couple hundred basis points. Contingent on a low 6-figures equity contribution (100K). They are interested in contributing a 2M note. 2026.03.25 Primer Project Hood Overview: Transaction est. 2013, target is womens subscription undergarments business with 41,600 active subscribers generating 8.7M and 620K in LTM Jan-26 Revenue and NOI, respectively 7.0 margin, being acquired at EV of 3.0M. Deal Structure: 2.8M cash at close, 480K seller note 8 rate, potential 600K note from interested sub-lender. Senior Ask 2.7-3.3M representing 31-38 of LTM ARR. Revenue 95 auto-renewing subscription. Key Risk: subscriber elasticity from January 2026 price increase.$n$
    WHERE company_id = bc_id AND (company ILIKE '%Splendies%' OR company ILIKE '%Level 7%');

  UPDATE public.deals SET narrative = $n$2026.01.30 JL Materials Review Notes: Transaction - why is management selling? management has implicitly agreed to a 5.2x LTM October 2025 QoE EBITDA multiple? Their original ask was 6.4x? you executed the first IOI in September of 2024. You reexecuted an IOI or LOI in early January 2026? What has been the holdup in the process? Why has the Seller agreed to continue working towards a transaction? are you the only horse in this race? What is the structure of the transaction? Financials: major single drug revenue concentration - top 2 drugs accounted for 90 of sales in 2025. Please elaborate on 20 revenue growth over past 3 years. Please help us understand the terms of your inventory purchasing - where is the cash coming from to make 200M of annual purchases? inventory was only 3M as of October 2025 despite 200M of annual purchases? 250K receivables writeoff last year. Value Prop Ocean Breeze: Is Ocean Breeze you selling DTC? does Ocean Breeze have exclusive right to the distribution of Omnitrope? Pharma company with one location in Staten Island pumping out 240M in revenue, 15-20M in EBITDA. Independent sponsor has LOI in place for 75M. 2 term sheets from hedge funds with spicy terms. Leaning on BCC to determine if better can be done.$n$
    WHERE company_id = bc_id AND company ILIKE '%Surevix%';

  UPDATE public.deals SET narrative = $n$Oak Proof Fund I, LP - JL connected with Todd on 2026.02.03 - Todd running a raw bourbon barrel purchasing fund. hold barrels as they age and sells them to bourbon brands in partnership with distilleries. he is a GP, gets a 2/20 like any PE sponsor. Todd suggesting it is time to strike in the market, pricing in continued demand deterioration to an overextended degree, making barrels available for discounts on already depressed numbers. supply is getting cut significantly faster than demand is pulling back. Todds base case model is a high-20s IRR. He is now closing up 4M Fund I and looking to launch 40-50M fund II - already in discussions with a family office considering putting up 10-15M in commitments. Ideally would want a 30M line to draw on. has been able to get 75 advances on appraised value of barrels at 14-15 rate, would prefer to get closer to 10. Team reconnected on 2026.02.10 - Time sensitive. JL followed up with Todd on 2026.02.22. JL connected with Todd on 2026.02.23 - sold the deal. Milestone fee of 30-40K. Will set at 35K. 1.5 of total commitment, 30M. JL sent proposal to Oak Proof LLC on 2026.02.25. JL followed up on 2026.03.03. JL followed up via text on 2026.03.05. 2026.02.23 Call Notes: Collateral - auditor in kentucky, blue and co. preference of an appraiser through venture first. annual appraisals. Title - lender gets lien on the title of the barrels. all barrels in an SPV. Storage - only acquiring barrels from handful of top distillers. existing storage agreements in place. fully insured, federally bonded. Contract Distillers: Lofted Spirits, Bardstown Bourbon Co, Green River and Whiskey House. Get a discount to fair market on new fill. Todd likely needs a warehouse facility 30M Revolver. Advance rates 60-75 of appraised barrel value. Collateral: bonded warehouse receipts, insurance assigned to lender, periodic valuation. Borrower: fund SPV.$n$
    WHERE company_id = bc_id AND company ILIKE '%Oak Proof%';

  UPDATE public.deals SET narrative = $n$JL Reachout Late January 2026: Lewis Pomeroy, Founding Partner, Hyndlaand IB, UK-based - 2026.02.04 - interested, will let marinate in spare time. Jeroen Hektor, Manager, EY Parthenon IB division, NL - 2026.01.23 - interested, will let marinate in spare time. Austin Foster, VP, Arma Partners IB, London - 2026.01.26 - interested, will let marinate in spare time. Damien Miller, MP Alpha Capital Fund Manager, London - 2026.01.22.$n$
    WHERE company_id = bc_id AND company ILIKE '%Club Condor%';

  UPDATE public.deals SET narrative = $n$JL connected with Bertrand on 2026.02.04 - looking to build 6 highly efficient greenhouse facilities across US, each 100M or so, addressing water shortage problems i.e. Texas, output will be cheaper products made with less water-intensiveness. Proof of concept at commercial stage with real blue-chip customers. Bertrand already has term sheets from international private credit firms in the single digits with 7-10 year term but wants longer duration capital. Total opp over next few years, 600M. Near-term, 100M existing facility in West Virginia, another 2 100-150M facilities in Texas in the coming 1-2 years. JL sent diligence request on 2026.02.$n$
    WHERE company_id = bc_id AND company ILIKE '%Water Garden%';
END $$;