DO $mig$
DECLARE
  bc_id uuid;
  d_id uuid;
  existing text;
  rec record;
  notes_data jsonb := $j$[
    {"name":"Club Five Health","note":"Team held meeting on 2026.01.20 with management. JL sent NDA and diligence request same day. JL connected with John Hanna on 2026.01.21 re feedback. Hanna suggested a bit too heavy handed on the deal being a heavy lift but management still keen to sign NDA and be responsive to diligence request list. Team on standby and to leverage Steve Landzberg construction equipment lending connections once materials on hand and teaser built out. JL to follow up 2026.01.27 if no word from management by then. JL to give founder, Ravi, a call on 2026.01.26. Ravi 2629893880. JL spoke to Ravi on 2026.01.26 - he indicated he was convinced and now will sign NDA and share documents, just concerned that we wont be able to raise the capital 5-10M - will be a facility that flexes with the size of the company, we as a responsible advisor dont want to put 20M on the business now anyway, would cripple it, facility size needs to scale with profitability."},
    {"name":"TriNeo Energy","note":"JL and GB holding kickoff call with Kirk at 3pm ET on 1/27. Per Kirk, in capital raising phase of renewable energy fund HOME / Trineo Energy Inc. 4 projects. getting project financing lined up for all. lenders currently circling. Kirk open to GB / JL opining to see what we can do on terms. looking for 60m of equity, 60m of debt. renewables project finance, KK acres of land, already well into permitting phases, interest from Microsoft and others re facilitation of data center buildouts on site, etc. Process sounds like its moving quickly. JL sent email on 2026.01.27 re request for NDA from Kirk - VDR already ready, JL to review and get back final week of January. Polly sent out email on 2026.02.09 with NDA to Kirk. JL to follow up with Kirk on executed copy and VDR 2nd week of february if nothing by then."},
    {"name":"BoxPort Capital","note":"JL connected with Adam on 2026.01.16. Import/export arbitrage model. Credible international banks hold security interest vs. end producers of goods, lending comfort re downside coverage. Adam requires more flexible capital partner than existing Greenwich-based PE firm that has provided 240M line to him, deployable in 20M monthly increments, as existing arrangement does not allow him to act quickly enough. Nature of the space is that deal windows are tight nature of arbitrage. Key is a partner who is nimble and can deploy bridge lending solutions at a moments notice but also has deep pockets. Additional consideration is this is a bit of a chicken and the egg situation, as Adam needs to build out a more formal team in order to lock in funding but needs the funding to support the team and deal generation. Team to connect with Adam on 2026.01.22 to further discuss."},
    {"name":"TicketVision","note":"Interesting ticketing arbitrage model. Partners with Stubhub and others. Offers the equivalent of a trading limit order in a DTC app allowing people to lock in preferred concert prices. Company has operated at 300K/mo in revenue at 41% profit margin for 2 years, per Dillon, founder. Team of 4-5 individuals. Implies roughly 3.5M of revenue, 1.5M of profit. Looking for capital, wants to explore what situations are available. Debrief scheduled for 3rd week of January. JL sent diligence request list on 2026.01.15. JL sent follow up via LinkedIn on 2026.05.21. been a handful of months. good for a catchup in the coming short weeks?"},
    {"name":"GenFuel","note":"Company performs organic recycling/refueling services, per John Hanna. JL discussed briefly with John Hanna on 2026.01.21. Hanna suggested waiting on board deck and financials from Company and will be back to JL in short-term. Nature of the opportunity is a bit opaque but sounds like a hybrid equipment financing / cash flow lending situation, as Hanna indicated the Company has positive cash flow and substantial assets. Unclear exactly what the capital will be used for."},
    {"name":"Jean-Pierre Klifa","note":"12 unit all-leased womens-wear dress retailer located in affluent, upper-tier FL beach towns. Owned and run by aging designer JPK. JPK looking to retire. Ask is 4.5M. Allegedly willing to hold 500K in seller note, perhaps can get him to stretch to 750K. Need likely 3.5-4M of debt. Company has generated 5M of revenue and 1M EBITDA for multiple years running with reportedly minimal working capital uses and maintenance capex as all locations are leased. JL worked with John Hanna in 2024-2025 in an attempt to acquire through Old Georgian Ventures. Turned down as was 500K short of ask. JPK was firm on value and went with another amateur SBA buyer, an arrangement which since fell through. John Hanna provided update on 2026.01.30 that JPK posted 1.4M in EBITDA in 2025. John submitted revised offer of 4M, 500K Seller, on 2026.02.17 post JL review of 2025 year end financials. 2026.02.23 - JL sent note to Hanna requesting NDA from company or joinder from banker ahead of opening up lender VDR. 2026.03.13 - JL to prepare and share underwriting memo with groups. 2026.03.16 JL prepared underwriting memo and shared with John Hanna. Awaiting approval and firming up on valuation ahead of sharing with Argosy, Gemini, CFP, NewTek, others. Spoke with John and Oscar on May 27th, 2026. Oscar has to take care of his personal issues. Once those are out of the way, we can move forward with him filling out the personal financial statements. With Ready Capital, Ready Capital thinks this is a pretty good deal. Its really just going to come down to is Oscar credit-worthy."},
    {"name":"EVRNU","note":"Recycled cotton and other materials. Huge Euro-based regulatory headwinds, cannot throw clothing into waste, has to be recycled. 3 patents. collaborations with burberry, zara. need 50M of financing. 30M accounted for by USDA but willing to go out and shop terms. 10M additional project equity needed, along with 10M more in operational funding. management is initially thinking equity but open to exploring mezzanine notes as well as other cheaper nondilutive solutions. As of 2026.01.27, next steps are getting VDR access. JL already sent NDA, client got back same day. Team then to get back latest 48 hours later with any questions and begin no-names reachout asap. Fantastic call with Bertrand Deleuse on 2026.02.12 - can farm the investors lining up for his greenhouse project for this. Good call with Stacy and Aidan on 2026.02.16. Call with Stacy and Aidan on 2026.02.25 went well. Sending Consulting agreement in short course for signing. Diligence session with Aidan on 2026.03.02. Sent over redline of CA same day. 2026.03.13 - team sent memo to Stacy and Aidan. Awaiting Consulting Agreement. 2026.03.17 team sent next cut of memo to Stacy and Aidan. Awaiting final comments."},
    {"name":"PiperWai","note":"Sarah Ribner, successful Shark Tank Alumn, has built impressive womens skincare retail brand with real revenue and EBITDA. looking to consolidate the beauty space later this year and Sarah expects she will need a debt partner, excited to have relationship with Blount. Sarah also passed along additional opportunity on 2026.02.02 re 1.3M funding gap in friends Series A, perhaps open to exploring non-dilutive solutions."},
    {"name":"Splendies","note":"I7 investments looking to facilitate e-commerce rollup strategy. Bryan Johnson, a startup strategic advisor, made intro to JL in late 2025. First management call held on 2026.01.23. JL connected with Yann on 2026.02.02. JL sent engagement agreement to Yann Com on 2026.02.12. Good call with Yann on 2026.02.17. JL sent Consulting Agreement and underwriting memo to Yann on 2026.03.01. JL introd Yann to Argosy and Commercial Finance Partners on 2026.03.04. JL introd to Founderpath on 2026.03.05. 2026.03.17 JL postponed call with Kevin Founderpath. JL to get Kevin NDA and memo WE 2026.03.20. 2026.03.27 JL sent note to Justin Rivera re 2-4x leverage cash flow lenders to use for Splendies, Barbaritas and Nippies."},
    {"name":"Candela","note":"Liquor brand. Production outsourced in South America. Company was sold to Diageo for LSD-MSD mm with lesser-developed branding and 1 SKU just after covid. Diageo has since divested. CEO since has doubled down and given the brand a complete facelift. Company will be cash flow breakeven at 1.5M revenue. 50% blended GM now. 60% with US broader distribution. 600K overhead. Losing 35K a month. Need 5M to fund purchase orders. Pit Bull an investor to the tune of low 6-figures. JL sent diligence request on 2026.01.02. JL followed up on materials on 2026.01.05. Russo sent over deck on 2026.01.09, still waiting on other financials. JL followed up with Russo on 2026.01.19 with email note. Waiting on full package as of 2026.01.21."},
    {"name":"ThinkClean","note":"Airport luggage sanitization solution. Currently a point-based, vendor solution, people pass through and can elect to use. Ultimate vision is to embed into airport infrastructure in partnership with SmarteCart. Currently pre-revenue but contracts in place at JFK and couple other major hubs. Company requires 1M to cover capital buildout cost of units 30-40K apiece. Low potential as an equipment financing play given the units do not have any known secondary use cases. Likely an equity story. Blount thinking through who can be introd to team, as of 2026.01.21, after 2026.01.20 meeting with Rodney. Rodney reached out to JL on 2026.01.29 requesting update. JL indicated awaiting feedback from a couple parties."},
    {"name":"Native Traits","note":"Corn yield enhancer. Seller of IP. Aim is to facilitate rollup strategy of players in the space. CEO claims significant potential for 1:13. But seems very early stage, not well thought out. Blount to spend little to no time here."},
    {"name":"Global Auto","note":"Tri-oceanic classic autos hedge fund opportunity. Uniting of Will Keiser of NY (WH Keiser Co, 30M HNW fund with long-term private capital), David Spickett of the UK (The Car Crowd, crowd-sourced fund, likely low 8 figures in AUM) and third fund David is introducing to us out of Australia. Major push here after big news mid-January 2026 of record setting classic autos prices. Blount submitted attached proposal in late 2025 - not willing to front 30K upfront fee but willing to give us equity. As of 2026.01.21, JL waiting on materials from David Spickett."},
    {"name":"NXTMoves","note":"Backend platform for banks looking to manage transaction data plus can perform in-house banking functions. Real traction, tracking to 8M in revenue in 2026. Coming off of a major customer roll-off that took sizable chunk out of revenue in 2024-2025. Good management meeting 2nd week of January 2026. Received VDR access on 2026.01.23. Team held call with management demo and diligence requests on 2026.01.28. Team caught up with Steve N on 2026.02.16, message being no bid for debt yet. To reconnect when company generating revenue - JL to follow up in May 2026. JL texted Steve N on 2026.02.24 - Blount happy to re-engage post-launch of programs in March when real proof of revenue."},
    {"name":"Compound Foundry","note":"Incredibly important relation. Terry Turpin multi-exit 9-figure entrepreneur. This is his latest venture. 60M revenue. 10% EBIT margins. Company growing out of its socks, only been around for 2 years. 2026 budget calls for 100M revenue, 10% EBIT margins. Company needs to get the house in order on the equipment financing side. Have disparate pieces of funding currently in place. Terry wants to clean up everything with one equipment financing line, indicated likely 5M need now, another 5M spread out through the year. JL followed up with Terry on 2026.01.21 via email. JL followed up on 2026.03.10 on LinkedIn. 2026.04.07 - JL sent text to Terry and left VM."},
    {"name":"Honor Pet","note":"Multi-exit founder. Very accomplished. Built 9-figure revenue businesses. Pet aftercare services. Looking for 1M in equity today. Help with intros. Eli passed along materials responsive to Blount diligence request on 2026.01.20. Team held call with Eli on 2026.01.23. JL prepared outreach email and sent to GB and BB on 2026.01.26. JL connected with Greg Doutre Priority Capital on 2026.02.03 - suggested may be of interest. BCC to share materials and VDR access with Greg 2nd week of February."},
    {"name":"Eflion","note":"Highly accomplished CFO, was named a top 25 CFO according to a reputable business publication in 2023. Currently working for a battery company looking to raise 30M. Has had some bad experiences with prior advisors charging upfront fees and accomplishing nothing. JL followed up with Yaser on 2026.01.21 after sharing NDA a couple weeks"}
  ]$j$::jsonb;
BEGIN
  SELECT id INTO bc_id FROM public.companies WHERE name = 'Blount Capital' LIMIT 1;
  IF bc_id IS NULL THEN RETURN; END IF;

  FOR rec IN
    SELECT name, string_agg(note, E'\n\n') AS note
    FROM jsonb_to_recordset(notes_data) AS x(name text, note text)
    GROUP BY name
  LOOP
    SELECT id, narrative INTO d_id, existing
      FROM public.deals
      WHERE company_id = bc_id AND company ILIKE '%' || rec.name || '%'
      LIMIT 1;

    IF d_id IS NULL THEN CONTINUE; END IF;
    IF existing IS NOT NULL AND position(left(rec.note, 100) in existing) > 0 THEN CONTINUE; END IF;

    UPDATE public.deals
       SET narrative = CASE
         WHEN narrative IS NULL OR length(btrim(narrative)) = 0 THEN rec.note
         ELSE narrative || E'\n\n' || rec.note
       END
     WHERE id = d_id;
  END LOOP;
END
$mig$;