DO $$
DECLARE
  bc_id uuid;
  d_id uuid;
  rec record;
  notes_data jsonb := '[
    {"name":"OpenDroids","note":"Very impressive, hype house founder. Hardware robotics company, selling into major manufacturers. Currently pre-revenue but have 11.8M contract that they need to scale into. CEO considering an IPO but likes the idea of pushing out 6-12 months to boost valuation. JL sent note to CFO contact, Varun, on 2026.01.19. Greg sent note to Varun on 2026.01.27 re condensed diligence request list and next steps. JL followed up yet again on 2026.02.03. JL sent following email on 2026.02.12 - happy to move on here. Were extremely busy on other fronts but are happy to help. We need direction regarding what pathway you want to go with. Sent SLandzberg materials on this on 2026.03.05."},
    {"name":"Tech-Enabled Services Refi","note":"CFO exploring a senior refinancing on behalf of an established tech-enabled services operator. Existing note has a current balance of 5M, paying cash PIK interest. The origination amount was 8M in early 2022. The Company generated 2.8M in EBITDA on 34.9M of Revenue in CY24. While 2025 actuals are being finalized, November 25 forecast called for 3.8M of CY25 EBITDA on 42.4M of Revenue. In 2026, Revenue and EBITDA are projected to climb to 67.9M and 5.1M, respectively. LTM interest coverage well exceeds 5x, with leverage of 2x. JL prepared draft email to be sent out to prospective lenders by GB."},
    {"name":"Phoenix Footwear","note":"Footwear brand getting crushed by international tariffs. 15-20M in revenue, breakeven EBITDA. Looking to acquire competitor to dig itself out. GB and JL connected with Jim on 2026.01.29 - Jim needs new AR/Inventory facility, 6M. GB JL awaiting package to assess feasibility. May pass along to distressed debt shops and take a fee. Package received on 2026.01.29. JL to review on 2026.01.31 to determine if feasible to get a replacement line on it."},
    {"name":"Voda Restoration","note":"Very impressive founder, long-standing relation of JL, built out franchisor providing facility maintenance services with 100+ franchisees, currently doing 20-30M revenue and 5M EBITDA. need 1-2M in funding now for scaling. JL sent NDA in Nov/December 2025. CFO has been slow walking. JL met with Dan on 2026.05.27 - Dan getting back to JL on data request same week. Dan shared materials on 2026.05.28."},
    {"name":"FarrPro","note":"Chicken Euthanasia N2 equipment financing. Major tailwinds in the space in the form of federal incentives. Need 2M to buy 4 machines that produce N2 bubbles. JL sent engagement letter 2nd week of January 2026. GB sent amended consulting engagement agreement and model on 2026.01.28. 2026.02.23 Call Action Items - JL to take stock of what we need, send comprehensive needs list to Luke, set up a call on Friday. 2026.02.27 call with Luke, walked through model. 2026.03.02 JL sent email with updated model. 2026.03.04 JL sent latest model reflecting changes discussed. 2026.03.09 JL shared latest model and first cut of memo with Amos and Luke. 2026.03.11 held call with Jeff. 2026.03.26 JL sent follow to Amos requesting feedback on memo. 2026.04.02 Amos shared latest investor deck. 2026.04.23 Process Email Sent to Luke and Amos re dual tracking debt and equity. Good catchup on 2026.05.28 with Luke - raising equity in michigan. JL waiting on financials from AES and actual transaction docs ahead of merger."},
    {"name":"Watches.com","note":"Opportunity to acquire the domain and the business. Run with a skeleton crew. Ask currently is 4.5M. GB going out to market with teaser JL prepared. Lender reachout beginning as of 2026.01.29. JL sent teaser to Founderpath. JL just spoke with lender - willing to lend 50% of revenues if all checks out. JL needs to find PIK mezzanine lender. John Hanna called JL on 2026.02.08 indicating he submitted 3M offer and ownership countered at 3M at close. 2026.02.17 - financials revised down to 550K of EBITDA - advertising spend was arbitrarily cut. JL requested that banker submit revised offer of 1.5M, 500K seller, on 2026.02.17. 2026.02.23 - JL sent note to Hanna requesting NDA. John Hanna clarified latest line in the sand is 2M, of which 500K seller note. Founderpath likely to be at 1.3-1.4M."},
    {"name":"Barbaritas","note":"Miami-based liquor distributor with 25M revenue, 5M EBITDA, 1 warehouse, 3 retail locations and special liquor license that John Hanna claims would render further FL expansion a layup. Business incredibly bare bones, dinosaur accounting system. Seller asking for 40M but John Hanna feels 35M would get it done. Buyer willing to hold 5-10M in Seller note. JL and John had call with banker on 2026.02.25. 2026.03.27 JL sent note to Justin Rivera re 2-4x leverage cash flow lenders to use for Splendies, Barbaritas and Nippies."},
    {"name":"California Cultured","note":"Cell-based manufacturer of alternative food products, cocoa is the focus. Alan Perlstein, the CEO, raising a 16M round, of which 8.5M is accounted for. Keen on exploring what kind of debt he can get as well. JL shared NDA and diligence request list with Alan in mid-January 2026. Alan yet to respond as of 2026.01.21. JL to follow up early February if no response by then."},
    {"name":"RxEbate","note":"Dividend recap for 60M revenue, 15M EBITDA medical rebate business. 70% owner pushing for dividend recap, 30% owner more hesitant. JL prepared model, merits, risks/mitigants on 2026.01.24. Latest model and deck sent to GB BB on 2026.01.27. Team connected with Jeff (65% owner) on 2026.01.28 - Jeff to get back to BCC after huddling with partner. Mizzen interested - 2.0x leverages, personal guarantee. Capitala SOFR + 5.50, 750-850bps, 5-year. S2K - reimbursement risk and no sponsor cash equity contribution. Concentric concerned about misalignment given lack of cash equity but may have some ideas. Commercial Finance Partners - very interested want to learn more."},
    {"name":"HoundCap","note":"Connection of Ruben Cotti-Lowell. Runs independent sponsor, Hound Capital. 30M deal, company purchased at ~2M EBITDA, now has 28M, heading for 50M this year. Call held on 2026.01.26 5pm ET. JL BB preparing redacted RxEbate deck to share as case study. JL sent out redacted RxEbate deck on 2026.01.27. Mark got back to JL on 2026.03.05. Mark got back to JL on 2026.05.25 - circle back in July of this year."},
    {"name":"Steam Bar","note":"Steve Landzberg to connect with Judy on 2026.01.26 to provide thoughts on the model ahead of sending model to John Hanna re equity intros. Steve Landzberg CFO call held on 2026.01.27 - Steve working on getting engaged and will likely take care of equity prospecting himself."},
    {"name":"Aurelux","note":"Discovery call scheduled with Alex on 2026.01.30. Referred by JL connection, Leroy Glass operates private jet leasing business."},
    {"name":"Insignary","note":"JL to review VDR on 2026.01.27 ahead of call later same week. JL prepared engagement proposal on 2026.02.05."},
    {"name":"Priority Capital","note":"JL floated in coffee chat on 2026.02.04 - Jace suggested may be interesting. JL to share materials when ready."},
    {"name":"UCEA","note":"GB / JL caught up with UCEA on 2026.02.05. Need events financing. 15-20K retainer upfront willing to pay. JL sent diligence request on 2026.02.05. JL followed up on 2026.02.22 to set up time to discuss. Some interest from Mizzen capital."},
    {"name":"Globe Metals","note":"Mizzen intro to bridge financers? 2026.02.10. Capitala to think about what bridge intros might make sense here."},
    {"name":"Surevix","note":"Mizzen is interested here, include in the VDR. Capitala generally dont do sponsor backed but still worth a look on this one. Pelham S2K - perhaps Linden capital could be interested but product concentration is nonstarter. Concentric - interested, 20M. 80/20 - 18M of debt and 2M of equity. Would be willing to work with a partner. Would not seek out scheduled amort, 5.5 years term length. looking for all cash pay and 12-13% all in. Commercial Finance Partners very interested - wants to look at it. Argosy Credit Partners willing to come in alongside another partner and potentially consider some equity piece. 12-15% rate, 3 year exit."},
    {"name":"Optivide","note":"JL spoke with founder on 2026.02.10 - nothing to do here, too small, too early, but may make some VC intros for the guy."},
    {"name":"Morfeu","note":"JL connected with founder on 2026.02.12 - raising 2M round for video content creation b2b/b2c company. raised 1M from turkish fund. open to nondilutive options for remaining 1M. JL thinks could be big - this founder already had 1 successful exit. JL sent diligence request list on 2026.02.12, along with NDA. Debrief meeting placeholder sent for 2026.02.25."},
    {"name":"Frontier Capital","note":"Connected on 2026.02.11 - property refi. JL followed up on 2026.03.05."},
    {"name":"Water Garden Farms","note":"JL to farm WGF investors from Bertrand Deleuse - perfect fit here. JL to set up convo with JP head of Sustainability Asset Management. JL followed up with Water Garden Farms on 2026.03.03. Lenders being considered include goldman sachs, macquarie, reboot capital, Eire Street, Essex, SX Capital, Texas Dept of Ag, ASI Infrastructure, Allshore Partners."},
    {"name":"Oak Proof","note":"2026.02.25 Terms Call With Todd Camhe. 3-5M of equity to fund opex in fund I. Dont want to sell barrels on their own or manage barrels. 13M in acquisition costs for barrels that will be appraised at 21M. Send proposal. If checks out with legal Todd wants to do this then send consulting agreement. Suggest in email setting up a group call with equity advisors."},
    {"name":"Buyside Fund Manager","note":"John Hanna indicated friend of his based in U.K. looking to raise credit fund to the tune of 50-100M to deploy into lower-mid-market companies and RE in Europe and UK."},
    {"name":"FFO Cannabis","note":"GB ran down 2nd week of January 2026. Too much grey area. Complicated, evolving space. Blount opted to be upfront with Tom rather than trying and coming back with nothing. Awaiting other deals from Tom he indicated he sees a lot."},
    {"name":"BlueNalu","note":"Cell-based high end tuna manufacturer responsive to mercury crisis. Require equipment financing in immediate term to the tune of 500K, then working capital funding ahead of cash low point in mid-26. If Blount can do these favors for the team, he will look to award us the big assignment of facility-buildout-funding - total cost expected to be 200-300M. JL shared NDA and diligence request list with CFO in early-mid-January 2026. JL connected with Greg Doutre Priority Capital on 2026.02.03. JL followed up with Ed on 2026.02.04. JL called Ed on 2026.04.08 and left VM and sent him an email. JL sent follow up on 2026.05.14."},
    {"name":"Eflion","note":"Highly accomplished CFO, was named a top 25 CFO in 2023. Currently working for a battery company looking to raise 30M. Has had some bad experiences with prior advisors charging upfront fees and accomplishing nothing. JL followed up with Yaser on 2026.01.21 after sharing NDA a couple weeks prior. To send Yaser LinkedIn note in addition to email if no response."},
    {"name":"Med Device","note":"Strong relationship of JL with healthcare sell-side banker in FL. 500K EBITDA med device manufacturer with real revenue that needs 5-10M to finance a facility/equipment buildout in order to deliver upon a contract that will springboard the company to 3M in EBITDA. Peter indicated management would be traveling until last week of January 2026. JL to reach out then to rekindle. Nice, sizable, potentially high probability opportunity."},
    {"name":"Urban Electric Power","note":"Zinc-ion battery manufacturer. High cost but also high safety rating. Good on operational capital at the moment with major Indian backer majority investor with deep pockets. Held conversation with Gabe in early january 2026. JL sent diligence request list. No response as of 2026.01.21. JL to follow up with Gabe last week of January."},
    {"name":"HealthFleet","note":"Anti-obesity, content-library platform now couched as a pathway that employers can make available to employees ahead of employees hopping on GLP-1 plans. Previously a much larger company, went through rationalization. Saved Caterpillar (CAT) 20M a year in costs. 80M in NOLs, company burning 100K a month. ARR financing a possibility but would likely not even get him 1M in debt vs. the 5-8M he is looking for. JL set up call with David Tradburks, a shell company NOL investor, and management, but David on 2026.01.20 indicated its a pass. JL to call David on 2026.01.22."},
    {"name":"BCC","note":"2026.02.27 JL prepared fundraising deck for 200K WC Raise."},
    {"name":"Club Condor","note":"2026.04.02 JL to update teaser and latest investor list and send by 2026.04.07, ahead of proposed call on 2026.04.08."},
    {"name":"Brown Rock","note":"16-18M Debt Raise for 35M Acquisition. Team held x2 calls with Darius on 2026.05.22. JL to share engagement proposal that evening. Engagement proposal discussion on 2026.06.01."},
    {"name":"Cristana Rocamora","note":"Property Refinancing. Engagement Proposal Sent on 2026.05.08. 30-Day Blount Exclusivity. Fee 4% of total financing commitment. No upfront fee."},
    {"name":"UrbanChain","note":"JL sent note on 2026.05.05 post-pitch to Client Vitaly. JL sent engagement proposal same day. GB sent follow up on 2026.05.28."},
    {"name":"Traffic Control","note":"JL called Tom on 2026.05.14 - business has 500K in lines today. May want more. JL sent note on 2026.05.28 re NDA and financials."}
  ]'::jsonb;
BEGIN
  SELECT id INTO bc_id FROM public.companies WHERE name = 'Blount Capital' LIMIT 1;
  IF bc_id IS NULL THEN RETURN; END IF;

  FOR rec IN SELECT * FROM jsonb_to_recordset(notes_data) AS x(name text, note text) LOOP
    SELECT id INTO d_id FROM public.deals
      WHERE company_id = bc_id AND company ILIKE '%' || rec.name || '%' LIMIT 1;

    IF d_id IS NOT NULL THEN
      UPDATE public.deals
         SET narrative = CASE
           WHEN narrative IS NULL OR length(btrim(narrative)) = 0 THEN rec.note
           WHEN position(left(rec.note, 100) in narrative) > 0 THEN narrative
           ELSE narrative || E'\n\n' || rec.note
         END
       WHERE id = d_id
         AND (narrative IS NULL OR position(left(rec.note, 100) in narrative) = 0
              OR length(btrim(narrative)) = 0);
    END IF;
    d_id := NULL;
  END LOOP;
END $$;